// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const categoryHasServices = `-- name: CategoryHasServices :one
SELECT EXISTS(SELECT 1 FROM default_services WHERE category_id = $1 AND is_active = TRUE) AS exists
`

func (q *Queries) CategoryHasServices(ctx context.Context, categoryID int32) (bool, error) {
	row := q.db.QueryRow(ctx, categoryHasServices, categoryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name) VALUES ($1)
RETURNING id, name, is_active, created_at, updated_at
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDefaultService = `-- name: CreateDefaultService :one
INSERT INTO default_services (category_id, slug, name, description, price, currency, duration_mins)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, category_id, slug, name, description, price, currency, duration_mins, is_active,
          created_at, updated_at
`

type CreateDefaultServiceParams struct {
	CategoryID   int32       `json:"category_id"`
	Slug         string      `json:"slug"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	Price        int32       `json:"price"`
	Currency     string      `json:"currency"`
	DurationMins int32       `json:"duration_mins"`
}

func (q *Queries) CreateDefaultService(ctx context.Context, arg CreateDefaultServiceParams) (DefaultService, error) {
	row := q.db.QueryRow(ctx, createDefaultService,
		arg.CategoryID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Currency,
		arg.DurationMins,
	)
	var i DefaultService
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.DurationMins,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const defaultServiceSlugExists = `-- name: DefaultServiceSlugExists :one
SELECT EXISTS(SELECT 1 FROM default_services WHERE slug = $1 AND id <> COALESCE($2, 0)) AS exists
`

type DefaultServiceSlugExistsParams struct {
	Slug      string      `json:"slug"`
	ExcludeID pgtype.Int4 `json:"exclude_id"`
}

func (q *Queries) DefaultServiceSlugExists(ctx context.Context, arg DefaultServiceSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, defaultServiceSlugExists, arg.Slug, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteCategory = `-- name: DeleteCategory :exec
UPDATE categories SET is_active = FALSE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const deleteDefaultService = `-- name: DeleteDefaultService :exec
UPDATE default_services SET is_active = FALSE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteDefaultService(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDefaultService, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, is_active, created_at, updated_at
FROM categories WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultService = `-- name: GetDefaultService :one
SELECT id, category_id, slug, name, description, price, currency, duration_mins, is_active,
       created_at, updated_at
FROM default_services WHERE id = $1
`

func (q *Queries) GetDefaultService(ctx context.Context, id int32) (DefaultService, error) {
	row := q.db.QueryRow(ctx, getDefaultService, id)
	var i DefaultService
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.DurationMins,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, is_active, created_at, updated_at
FROM categories
WHERE is_active = TRUE
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDefaultServices = `-- name: ListDefaultServices :many
SELECT id, category_id, slug, name, description, price, currency, duration_mins, is_active,
       created_at, updated_at
FROM default_services
WHERE is_active = TRUE
  AND ($1::int IS NULL OR category_id = $1)
ORDER BY name
`

func (q *Queries) ListDefaultServices(ctx context.Context, categoryID pgtype.Int4) ([]DefaultService, error) {
	rows, err := q.db.Query(ctx, listDefaultServices, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DefaultService
	for rows.Next() {
		var i DefaultService
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.DurationMins,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, is_active, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDefaultService = `-- name: UpdateDefaultService :one
UPDATE default_services
SET slug          = COALESCE($1, slug),
    name          = COALESCE($2, name),
    description   = COALESCE($3, description),
    duration_mins = COALESCE($4, duration_mins),
    price         = COALESCE($5, price),
    updated_at    = NOW()
WHERE id = $6
RETURNING id, category_id, slug, name, description, price, currency, duration_mins, is_active,
          created_at, updated_at
`

type UpdateDefaultServiceParams struct {
	Slug         pgtype.Text `json:"slug"`
	Name         pgtype.Text `json:"name"`
	Description  pgtype.Text `json:"description"`
	DurationMins pgtype.Int4 `json:"duration_mins"`
	Price        pgtype.Int4 `json:"price"`
	ID           int32       `json:"id"`
}

func (q *Queries) UpdateDefaultService(ctx context.Context, arg UpdateDefaultServiceParams) (DefaultService, error) {
	row := q.db.QueryRow(ctx, updateDefaultService,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.DurationMins,
		arg.Price,
		arg.ID,
	)
	var i DefaultService
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.DurationMins,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
