// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exceptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createException = `-- name: CreateException :one
INSERT INTO exceptions (
    location_id, date, type, is_full_day,
    custom_start, custom_end, rest_start, rest_end, reason
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, location_id, date, type, is_full_day,
          custom_start, custom_end, rest_start, rest_end,
          reason, created_at, updated_at
`

type CreateExceptionParams struct {
	LocationID  int32       `json:"location_id"`
	Date        pgtype.Date `json:"date"`
	Type        int16       `json:"type"`
	IsFullDay   bool        `json:"is_full_day"`
	CustomStart pgtype.Time `json:"custom_start"`
	CustomEnd   pgtype.Time `json:"custom_end"`
	RestStart   pgtype.Time `json:"rest_start"`
	RestEnd     pgtype.Time `json:"rest_end"`
	Reason      pgtype.Text `json:"reason"`
}

func (q *Queries) CreateException(ctx context.Context, arg CreateExceptionParams) (Exception, error) {
	row := q.db.QueryRow(ctx, createException,
		arg.LocationID,
		arg.Date,
		arg.Type,
		arg.IsFullDay,
		arg.CustomStart,
		arg.CustomEnd,
		arg.RestStart,
		arg.RestEnd,
		arg.Reason,
	)
	var i Exception
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Date,
		&i.Type,
		&i.IsFullDay,
		&i.CustomStart,
		&i.CustomEnd,
		&i.RestStart,
		&i.RestEnd,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteException = `-- name: DeleteException :exec
DELETE FROM exceptions WHERE id = $1
`

func (q *Queries) DeleteException(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteException, id)
	return err
}

const deleteExceptionByLocationAndDate = `-- name: DeleteExceptionByLocationAndDate :exec
DELETE FROM exceptions WHERE location_id = $1 AND date = $2
`

type DeleteExceptionByLocationAndDateParams struct {
	LocationID int32       `json:"location_id"`
	Date       pgtype.Date `json:"date"`
}

func (q *Queries) DeleteExceptionByLocationAndDate(ctx context.Context, arg DeleteExceptionByLocationAndDateParams) error {
	_, err := q.db.Exec(ctx, deleteExceptionByLocationAndDate, arg.LocationID, arg.Date)
	return err
}

const exceptionBelongsToLocation = `-- name: ExceptionBelongsToLocation :one
SELECT EXISTS(
    SELECT 1 FROM exceptions WHERE id = $1 AND location_id = $2
) AS belongs
`

type ExceptionBelongsToLocationParams struct {
	ID         int32 `json:"id"`
	LocationID int32 `json:"location_id"`
}

func (q *Queries) ExceptionBelongsToLocation(ctx context.Context, arg ExceptionBelongsToLocationParams) (bool, error) {
	row := q.db.QueryRow(ctx, exceptionBelongsToLocation, arg.ID, arg.LocationID)
	var belongs bool
	err := row.Scan(&belongs)
	return belongs, err
}

const getExceptionByLocationAndDate = `-- name: GetExceptionByLocationAndDate :one
SELECT
    id, location_id, date, type, is_full_day,
    custom_start, custom_end, rest_start, rest_end,
    reason, created_at, updated_at
FROM exceptions
WHERE location_id = $1 AND date = $2
`

type GetExceptionByLocationAndDateParams struct {
	LocationID int32       `json:"location_id"`
	Date       pgtype.Date `json:"date"`
}

func (q *Queries) GetExceptionByLocationAndDate(ctx context.Context, arg GetExceptionByLocationAndDateParams) (Exception, error) {
	row := q.db.QueryRow(ctx, getExceptionByLocationAndDate, arg.LocationID, arg.Date)
	var i Exception
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Date,
		&i.Type,
		&i.IsFullDay,
		&i.CustomStart,
		&i.CustomEnd,
		&i.RestStart,
		&i.RestEnd,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExceptionsByLocationAndRange = `-- name: GetExceptionsByLocationAndRange :many
SELECT
    id, location_id, date, type, is_full_day,
    custom_start, custom_end, rest_start, rest_end,
    reason, created_at, updated_at
FROM exceptions
WHERE location_id = $1
  AND date BETWEEN $2::date AND $3::date
ORDER BY date
`

type GetExceptionsByLocationAndRangeParams struct {
	LocationID int32       `json:"location_id"`
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
}

func (q *Queries) GetExceptionsByLocationAndRange(ctx context.Context, arg GetExceptionsByLocationAndRangeParams) ([]Exception, error) {
	rows, err := q.db.Query(ctx, getExceptionsByLocationAndRange, arg.LocationID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exception
	for rows.Next() {
		var i Exception
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Date,
			&i.Type,
			&i.IsFullDay,
			&i.CustomStart,
			&i.CustomEnd,
			&i.RestStart,
			&i.RestEnd,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
