// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveLocationsByMaster = `-- name: CountActiveLocationsByMaster :one
SELECT COUNT(*) FROM locations
WHERE master_id = $1 AND is_active = TRUE
`

func (q *Queries) CountActiveLocationsByMaster(ctx context.Context, masterID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveLocationsByMaster, masterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (master_id, name, address, timezone, is_online, meeting_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, master_id, name, address, timezone, is_online, meeting_url, is_active,
          created_at, updated_at
`

type CreateLocationParams struct {
	MasterID   int32       `json:"master_id"`
	Name       string      `json:"name"`
	Address    string      `json:"address"`
	Timezone   string      `json:"timezone"`
	IsOnline   pgtype.Bool `json:"is_online"`
	MeetingUrl pgtype.Text `json:"meeting_url"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.MasterID,
		arg.Name,
		arg.Address,
		arg.Timezone,
		arg.IsOnline,
		arg.MeetingUrl,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.Name,
		&i.Address,
		&i.Timezone,
		&i.IsOnline,
		&i.MeetingUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT
    id, master_id, name, address, timezone, is_online, meeting_url, is_active,
    created_at, updated_at
FROM locations
WHERE id = $1
`

func (q *Queries) GetLocationByID(ctx context.Context, id int32) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.Name,
		&i.Address,
		&i.Timezone,
		&i.IsOnline,
		&i.MeetingUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocationsByMaster = `-- name: ListLocationsByMaster :many
SELECT
    id, master_id, name, address, timezone, is_online, meeting_url, is_active,
    created_at, updated_at
FROM locations
WHERE master_id = $1
  AND ($2::bool IS NULL OR is_active = $2)
ORDER BY id
`

type ListLocationsByMasterParams struct {
	MasterID   int32       `json:"master_id"`
	OnlyActive pgtype.Bool `json:"only_active"`
}

func (q *Queries) ListLocationsByMaster(ctx context.Context, arg ListLocationsByMasterParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocationsByMaster, arg.MasterID, arg.OnlyActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.MasterID,
			&i.Name,
			&i.Address,
			&i.Timezone,
			&i.IsOnline,
			&i.MeetingUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationBelongsToMaster = `-- name: LocationBelongsToMaster :one
SELECT EXISTS(
    SELECT 1 FROM locations WHERE id = $1 AND master_id = $2
) AS belongs
`

type LocationBelongsToMasterParams struct {
	ID       int32 `json:"id"`
	MasterID int32 `json:"master_id"`
}

func (q *Queries) LocationBelongsToMaster(ctx context.Context, arg LocationBelongsToMasterParams) (bool, error) {
	row := q.db.QueryRow(ctx, locationBelongsToMaster, arg.ID, arg.MasterID)
	var belongs bool
	err := row.Scan(&belongs)
	return belongs, err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET name        = COALESCE($1, name),
    address     = COALESCE($2, address),
    timezone    = COALESCE($3, timezone),
    is_online   = COALESCE($4, is_online),
    meeting_url = COALESCE($5, meeting_url),
    is_active   = COALESCE($6, is_active),
    updated_at  = NOW()
WHERE id = $7
RETURNING id, master_id, name, address, timezone, is_online, meeting_url, is_active,
          created_at, updated_at
`

type UpdateLocationParams struct {
	Name       pgtype.Text `json:"name"`
	Address    pgtype.Text `json:"address"`
	Timezone   pgtype.Text `json:"timezone"`
	IsOnline   pgtype.Bool `json:"is_online"`
	MeetingUrl pgtype.Text `json:"meeting_url"`
	IsActive   pgtype.Bool `json:"is_active"`
	ID         int32       `json:"id"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.Name,
		arg.Address,
		arg.Timezone,
		arg.IsOnline,
		arg.MeetingUrl,
		arg.IsActive,
		arg.ID,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.Name,
		&i.Address,
		&i.Timezone,
		&i.IsOnline,
		&i.MeetingUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
