// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: masters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMaster = `-- name: CreateMaster :one
INSERT INTO masters (user_id, slug, bio, specialization, years_of_experience, is_accepting_bookings)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, slug, bio, specialization, years_of_experience,
          is_accepting_bookings, default_location_id, min_price, avg_rating, reviews_count,
          created_at, updated_at
`

type CreateMasterParams struct {
	UserID              int32       `json:"user_id"`
	Slug                string      `json:"slug"`
	Bio                 pgtype.Text `json:"bio"`
	Specialization      string      `json:"specialization"`
	YearsOfExperience   int32       `json:"years_of_experience"`
	IsAcceptingBookings pgtype.Bool `json:"is_accepting_bookings"`
}

func (q *Queries) CreateMaster(ctx context.Context, arg CreateMasterParams) (Master, error) {
	row := q.db.QueryRow(ctx, createMaster,
		arg.UserID,
		arg.Slug,
		arg.Bio,
		arg.Specialization,
		arg.YearsOfExperience,
		arg.IsAcceptingBookings,
	)
	var i Master
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Bio,
		&i.Specialization,
		&i.YearsOfExperience,
		&i.IsAcceptingBookings,
		&i.DefaultLocationID,
		&i.MinPrice,
		&i.AvgRating,
		&i.ReviewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMasterBySlug = `-- name: GetMasterBySlug :one
SELECT
    m.id, m.user_id, m.slug, m.bio, m.specialization, m.years_of_experience,
    m.is_accepting_bookings, m.default_location_id,
    m.min_price, m.avg_rating, m.reviews_count,
    m.created_at, m.updated_at,

    u.name          AS user_name,
    u.email         AS user_email,
    u.avatar_url    AS user_avatar_url,
    u.timezone      AS user_timezone,
    u.email_verified AS user_email_verified,
    (SELECT array_agg(ur.role_id ORDER BY ur.role_id)
     FROM user_roles ur WHERE ur.user_id = u.id)::int[] AS user_role_ids,

    COALESCE((
        SELECT json_agg(json_build_object(
            'id', s.id, 'name', s.name, 'slug', s.slug, 'description', s.description,
            'price', s.price, 'duration_mins', s.duration_mins, 'is_active', s.is_active
        ) ORDER BY s.price ASC)
        FROM services s WHERE s.master_id = m.id AND s.is_active = TRUE
    ), '[]'::json) AS services_json

FROM masters m
JOIN users u ON u.id = m.user_id
WHERE m.slug = $1
`

type GetMasterBySlugRow struct {
	ID                  int32              `json:"id"`
	UserID              int32              `json:"user_id"`
	Slug                string             `json:"slug"`
	Bio                 pgtype.Text        `json:"bio"`
	Specialization      string             `json:"specialization"`
	YearsOfExperience   int32              `json:"years_of_experience"`
	IsAcceptingBookings pgtype.Bool        `json:"is_accepting_bookings"`
	DefaultLocationID   pgtype.Int4        `json:"default_location_id"`
	MinPrice            pgtype.Int4        `json:"min_price"`
	AvgRating           pgtype.Numeric     `json:"avg_rating"`
	ReviewsCount        pgtype.Int4        `json:"reviews_count"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	UserName            pgtype.Text        `json:"user_name"`
	UserEmail           string             `json:"user_email"`
	UserAvatarUrl       pgtype.Text        `json:"user_avatar_url"`
	UserTimezone        pgtype.Text        `json:"user_timezone"`
	UserEmailVerified   pgtype.Bool        `json:"user_email_verified"`
	UserRoleIds         []int32            `json:"user_role_ids"`
	ServicesJson        interface{}        `json:"services_json"`
}

func (q *Queries) GetMasterBySlug(ctx context.Context, slug string) (GetMasterBySlugRow, error) {
	row := q.db.QueryRow(ctx, getMasterBySlug, slug)
	var i GetMasterBySlugRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Bio,
		&i.Specialization,
		&i.YearsOfExperience,
		&i.IsAcceptingBookings,
		&i.DefaultLocationID,
		&i.MinPrice,
		&i.AvgRating,
		&i.ReviewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
		&i.UserAvatarUrl,
		&i.UserTimezone,
		&i.UserEmailVerified,
		&i.UserRoleIds,
		&i.ServicesJson,
	)
	return i, err
}

const getMasterByUserID = `-- name: GetMasterByUserID :one
SELECT
    m.id, m.user_id, m.slug, m.bio, m.specialization, m.years_of_experience,
    m.is_accepting_bookings, m.default_location_id,
    m.min_price, m.avg_rating, m.reviews_count,
    m.created_at, m.updated_at,

    u.name          AS user_name,
    u.email         AS user_email,
    u.avatar_url    AS user_avatar_url,
    u.timezone      AS user_timezone,
    u.email_verified AS user_email_verified,
    (SELECT array_agg(ur.role_id ORDER BY ur.role_id)
     FROM user_roles ur WHERE ur.user_id = u.id)::int[] AS user_role_ids,

    COALESCE((
        SELECT json_agg(json_build_object(
            'id', s.id, 'name', s.name, 'slug', s.slug, 'description', s.description,
            'price', s.price, 'duration_mins', s.duration_mins, 'is_active', s.is_active
        ) ORDER BY s.price ASC)
        FROM services s WHERE s.master_id = m.id AND s.is_active = TRUE
    ), '[]'::json) AS services_json

FROM masters m
JOIN users u ON u.id = m.user_id
WHERE m.user_id = $1
`

type GetMasterByUserIDRow struct {
	ID                  int32              `json:"id"`
	UserID              int32              `json:"user_id"`
	Slug                string             `json:"slug"`
	Bio                 pgtype.Text        `json:"bio"`
	Specialization      string             `json:"specialization"`
	YearsOfExperience   int32              `json:"years_of_experience"`
	IsAcceptingBookings pgtype.Bool        `json:"is_accepting_bookings"`
	DefaultLocationID   pgtype.Int4        `json:"default_location_id"`
	MinPrice            pgtype.Int4        `json:"min_price"`
	AvgRating           pgtype.Numeric     `json:"avg_rating"`
	ReviewsCount        pgtype.Int4        `json:"reviews_count"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	UserName            pgtype.Text        `json:"user_name"`
	UserEmail           string             `json:"user_email"`
	UserAvatarUrl       pgtype.Text        `json:"user_avatar_url"`
	UserTimezone        pgtype.Text        `json:"user_timezone"`
	UserEmailVerified   pgtype.Bool        `json:"user_email_verified"`
	UserRoleIds         []int32            `json:"user_role_ids"`
	ServicesJson        interface{}        `json:"services_json"`
}

func (q *Queries) GetMasterByUserID(ctx context.Context, userID int32) (GetMasterByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getMasterByUserID, userID)
	var i GetMasterByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Bio,
		&i.Specialization,
		&i.YearsOfExperience,
		&i.IsAcceptingBookings,
		&i.DefaultLocationID,
		&i.MinPrice,
		&i.AvgRating,
		&i.ReviewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
		&i.UserAvatarUrl,
		&i.UserTimezone,
		&i.UserEmailVerified,
		&i.UserRoleIds,
		&i.ServicesJson,
	)
	return i, err
}

const getMasterCertificates = `-- name: GetMasterCertificates :many
SELECT id, name, organization, year, file_url FROM certificates WHERE master_id = $1
`

type GetMasterCertificatesRow struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	Organization string `json:"organization"`
	Year         int32  `json:"year"`
	FileUrl      string `json:"file_url"`
}

func (q *Queries) GetMasterCertificates(ctx context.Context, masterID int32) ([]GetMasterCertificatesRow, error) {
	rows, err := q.db.Query(ctx, getMasterCertificates, masterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMasterCertificatesRow
	for rows.Next() {
		var i GetMasterCertificatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Organization,
			&i.Year,
			&i.FileUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMasterIDByUserID = `-- name: GetMasterIDByUserID :one
SELECT id FROM masters WHERE user_id = $1
`

func (q *Queries) GetMasterIDByUserID(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getMasterIDByUserID, userID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getMasterLanguages = `-- name: GetMasterLanguages :many
SELECT language, proficiency FROM languages WHERE master_id = $1
`

type GetMasterLanguagesRow struct {
	Language    string           `json:"language"`
	Proficiency ProficiencyLevel `json:"proficiency"`
}

func (q *Queries) GetMasterLanguages(ctx context.Context, masterID int32) ([]GetMasterLanguagesRow, error) {
	rows, err := q.db.Query(ctx, getMasterLanguages, masterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMasterLanguagesRow
	for rows.Next() {
		var i GetMasterLanguagesRow
		if err := rows.Scan(&i.Language, &i.Proficiency); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMasterCertificates = `-- name: InsertMasterCertificates :exec
INSERT INTO certificates (master_id, name, organization, year, file_url)
SELECT
    $1::int,
    x.name,
    x.organization,
    x.year,
    x.file_url
FROM jsonb_to_recordset($2::jsonb)
     AS x(name TEXT, organization TEXT, year INT, file_url TEXT)
`

type InsertMasterCertificatesParams struct {
	MasterID int32  `json:"master_id"`
	Data     []byte `json:"data"`
}

func (q *Queries) InsertMasterCertificates(ctx context.Context, arg InsertMasterCertificatesParams) error {
	_, err := q.db.Exec(ctx, insertMasterCertificates, arg.MasterID, arg.Data)
	return err
}

const insertMasterLanguages = `-- name: InsertMasterLanguages :exec
INSERT INTO languages (master_id, language, proficiency)
SELECT $1, x.language, x.proficiency::proficiency_level
FROM jsonb_to_recordset($2::jsonb)
     AS x(language TEXT, proficiency TEXT)
`

type InsertMasterLanguagesParams struct {
	MasterID int32  `json:"master_id"`
	Data     []byte `json:"data"`
}

func (q *Queries) InsertMasterLanguages(ctx context.Context, arg InsertMasterLanguagesParams) error {
	_, err := q.db.Exec(ctx, insertMasterLanguages, arg.MasterID, arg.Data)
	return err
}

const listMastersByExperience = `-- name: ListMastersByExperience :many
SELECT
    m.id, m.user_id, m.slug, m.bio, m.specialization, m.years_of_experience,
    m.is_accepting_bookings, m.default_location_id,
    m.min_price, m.avg_rating, m.reviews_count,
    m.created_at, m.updated_at,

    u.name          AS user_name,
    u.email         AS user_email,
    u.avatar_url    AS user_avatar_url,
    u.timezone      AS user_timezone,
    u.email_verified AS user_email_verified,
    (SELECT array_agg(ur.role_id ORDER BY ur.role_id)
     FROM user_roles ur WHERE ur.user_id = u.id)::int[] AS user_role_ids,

    COALESCE((
        SELECT json_agg(json_build_object(
            'id', l.id, 'name', l.name, 'address', l.address,
            'timezone', l.timezone, 'is_online', l.is_online, 'meeting_url', l.meeting_url
        ) ORDER BY l.id)
        FROM locations l WHERE l.master_id = m.id AND l.is_active = TRUE
    ), '[]'::json) AS locations_json,

    COALESCE((
        SELECT json_agg(json_build_object(
            'id', s.id, 'name', s.name, 'slug', s.slug,
            'price', s.price, 'duration_mins', s.duration_mins
        ) ORDER BY s.price ASC)
        FROM (
            SELECT id, name, slug, price, duration_mins
            FROM services
            WHERE master_id = m.id AND is_active = TRUE
            ORDER BY price ASC
            LIMIT 3
        ) s
    ), '[]'::json) AS top_services_json,

    (SELECT COUNT(*) FROM services
     WHERE master_id = m.id AND is_active = TRUE) AS total_services

FROM masters m
JOIN users u ON u.id = m.user_id
WHERE m.is_accepting_bookings = TRUE
  AND ($1::int      IS NULL OR m.min_price >= $1)
  AND ($2::int      IS NULL OR m.min_price <= $2)
  AND ($3::int IS NULL OR m.years_of_experience >= $3)
  AND ($4::text IS NULL OR m.specialization = $4)
  AND ($5::text IS NULL OR u.timezone = $5)
  AND ($6::int IS NULL OR EXISTS (
        SELECT 1 FROM services s
        WHERE s.master_id = m.id AND s.id = $6 AND s.is_active = TRUE
  ))
  AND ($7::int IS NULL
       OR (m.years_of_experience, m.id) < ($7, $8))
ORDER BY m.years_of_experience DESC, m.id DESC
LIMIT $9
`

type ListMastersByExperienceParams struct {
	MinPrice         pgtype.Int4 `json:"min_price"`
	MaxPrice         pgtype.Int4 `json:"max_price"`
	MinExperience    pgtype.Int4 `json:"min_experience"`
	Specialization   pgtype.Text `json:"specialization"`
	MasterTimezone   pgtype.Text `json:"master_timezone"`
	ServiceID        pgtype.Int4 `json:"service_id"`
	CursorExperience pgtype.Int4 `json:"cursor_experience"`
	CursorID         pgtype.Int4 `json:"cursor_id"`
	PageSize         int32       `json:"page_size"`
}

type ListMastersByExperienceRow struct {
	ID                  int32              `json:"id"`
	UserID              int32              `json:"user_id"`
	Slug                string             `json:"slug"`
	Bio                 pgtype.Text        `json:"bio"`
	Specialization      string             `json:"specialization"`
	YearsOfExperience   int32              `json:"years_of_experience"`
	IsAcceptingBookings pgtype.Bool        `json:"is_accepting_bookings"`
	DefaultLocationID   pgtype.Int4        `json:"default_location_id"`
	MinPrice            pgtype.Int4        `json:"min_price"`
	AvgRating           pgtype.Numeric     `json:"avg_rating"`
	ReviewsCount        pgtype.Int4        `json:"reviews_count"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	UserName            pgtype.Text        `json:"user_name"`
	UserEmail           string             `json:"user_email"`
	UserAvatarUrl       pgtype.Text        `json:"user_avatar_url"`
	UserTimezone        pgtype.Text        `json:"user_timezone"`
	UserEmailVerified   pgtype.Bool        `json:"user_email_verified"`
	UserRoleIds         []int32            `json:"user_role_ids"`
	LocationsJson       interface{}        `json:"locations_json"`
	TopServicesJson     interface{}        `json:"top_services_json"`
	TotalServices       int64              `json:"total_services"`
}

func (q *Queries) ListMastersByExperience(ctx context.Context, arg ListMastersByExperienceParams) ([]ListMastersByExperienceRow, error) {
	rows, err := q.db.Query(ctx, listMastersByExperience,
		arg.MinPrice,
		arg.MaxPrice,
		arg.MinExperience,
		arg.Specialization,
		arg.MasterTimezone,
		arg.ServiceID,
		arg.CursorExperience,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMastersByExperienceRow
	for rows.Next() {
		var i ListMastersByExperienceRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.Bio,
			&i.Specialization,
			&i.YearsOfExperience,
			&i.IsAcceptingBookings,
			&i.DefaultLocationID,
			&i.MinPrice,
			&i.AvgRating,
			&i.ReviewsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
			&i.UserTimezone,
			&i.UserEmailVerified,
			&i.UserRoleIds,
			&i.LocationsJson,
			&i.TopServicesJson,
			&i.TotalServices,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMastersByPrice = `-- name: ListMastersByPrice :many
SELECT
    m.id, m.user_id, m.slug, m.bio, m.specialization, m.years_of_experience,
    m.is_accepting_bookings, m.default_location_id,
    m.min_price, m.avg_rating, m.reviews_count,
    m.created_at, m.updated_at,

    u.name          AS user_name,
    u.email         AS user_email,
    u.avatar_url    AS user_avatar_url,
    u.timezone      AS user_timezone,
    u.email_verified AS user_email_verified,
    (SELECT array_agg(ur.role_id ORDER BY ur.role_id)
     FROM user_roles ur WHERE ur.user_id = u.id)::int[] AS user_role_ids,

    COALESCE((
        SELECT json_agg(json_build_object(
            'id', l.id, 'name', l.name, 'address', l.address,
            'timezone', l.timezone, 'is_online', l.is_online, 'meeting_url', l.meeting_url
        ) ORDER BY l.id)
        FROM locations l WHERE l.master_id = m.id AND l.is_active = TRUE
    ), '[]'::json) AS locations_json,

    COALESCE((
        SELECT json_agg(json_build_object(
            'id', s.id, 'name', s.name, 'slug', s.slug,
            'price', s.price, 'duration_mins', s.duration_mins
        ) ORDER BY s.price ASC)
        FROM (
            SELECT id, name, slug, price, duration_mins
            FROM services
            WHERE master_id = m.id AND is_active = TRUE
            ORDER BY price ASC
            LIMIT 3
        ) s
    ), '[]'::json) AS top_services_json,

    (SELECT COUNT(*) FROM services
     WHERE master_id = m.id AND is_active = TRUE) AS total_services

FROM masters m
JOIN users u ON u.id = m.user_id
WHERE m.is_accepting_bookings = TRUE
  AND ($1::int      IS NULL OR m.min_price >= $1)
  AND ($2::int      IS NULL OR m.min_price <= $2)
  AND ($3::int IS NULL OR m.years_of_experience >= $3)
  AND ($4::text IS NULL OR m.specialization = $4)
  AND ($5::text IS NULL OR u.timezone = $5)
  AND ($6::int IS NULL OR EXISTS (
        SELECT 1 FROM services s
        WHERE s.master_id = m.id AND s.id = $6 AND s.is_active = TRUE
  ))
  AND ($7::int IS NULL
       OR (m.min_price, m.id) > ($7, $8))
ORDER BY m.min_price ASC, m.id ASC
LIMIT $9
`

type ListMastersByPriceParams struct {
	MinPrice       pgtype.Int4 `json:"min_price"`
	MaxPrice       pgtype.Int4 `json:"max_price"`
	MinExperience  pgtype.Int4 `json:"min_experience"`
	Specialization pgtype.Text `json:"specialization"`
	MasterTimezone pgtype.Text `json:"master_timezone"`
	ServiceID      pgtype.Int4 `json:"service_id"`
	CursorPrice    pgtype.Int4 `json:"cursor_price"`
	CursorID       pgtype.Int4 `json:"cursor_id"`
	PageSize       int32       `json:"page_size"`
}

type ListMastersByPriceRow struct {
	ID                  int32              `json:"id"`
	UserID              int32              `json:"user_id"`
	Slug                string             `json:"slug"`
	Bio                 pgtype.Text        `json:"bio"`
	Specialization      string             `json:"specialization"`
	YearsOfExperience   int32              `json:"years_of_experience"`
	IsAcceptingBookings pgtype.Bool        `json:"is_accepting_bookings"`
	DefaultLocationID   pgtype.Int4        `json:"default_location_id"`
	MinPrice            pgtype.Int4        `json:"min_price"`
	AvgRating           pgtype.Numeric     `json:"avg_rating"`
	ReviewsCount        pgtype.Int4        `json:"reviews_count"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	UserName            pgtype.Text        `json:"user_name"`
	UserEmail           string             `json:"user_email"`
	UserAvatarUrl       pgtype.Text        `json:"user_avatar_url"`
	UserTimezone        pgtype.Text        `json:"user_timezone"`
	UserEmailVerified   pgtype.Bool        `json:"user_email_verified"`
	UserRoleIds         []int32            `json:"user_role_ids"`
	LocationsJson       interface{}        `json:"locations_json"`
	TopServicesJson     interface{}        `json:"top_services_json"`
	TotalServices       int64              `json:"total_services"`
}

func (q *Queries) ListMastersByPrice(ctx context.Context, arg ListMastersByPriceParams) ([]ListMastersByPriceRow, error) {
	rows, err := q.db.Query(ctx, listMastersByPrice,
		arg.MinPrice,
		arg.MaxPrice,
		arg.MinExperience,
		arg.Specialization,
		arg.MasterTimezone,
		arg.ServiceID,
		arg.CursorPrice,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMastersByPriceRow
	for rows.Next() {
		var i ListMastersByPriceRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.Bio,
			&i.Specialization,
			&i.YearsOfExperience,
			&i.IsAcceptingBookings,
			&i.DefaultLocationID,
			&i.MinPrice,
			&i.AvgRating,
			&i.ReviewsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
			&i.UserTimezone,
			&i.UserEmailVerified,
			&i.UserRoleIds,
			&i.LocationsJson,
			&i.TopServicesJson,
			&i.TotalServices,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMastersByRating = `-- name: ListMastersByRating :many
SELECT
    m.id, m.user_id, m.slug, m.bio, m.specialization, m.years_of_experience,
    m.is_accepting_bookings, m.default_location_id,
    m.min_price, m.avg_rating, m.reviews_count,
    m.created_at, m.updated_at,

    u.name          AS user_name,
    u.email         AS user_email,
    u.avatar_url    AS user_avatar_url,
    u.timezone      AS user_timezone,
    u.email_verified AS user_email_verified,
    (SELECT array_agg(ur.role_id ORDER BY ur.role_id)
     FROM user_roles ur WHERE ur.user_id = u.id)::int[] AS user_role_ids,

    COALESCE((
        SELECT json_agg(json_build_object(
            'id', l.id, 'name', l.name, 'address', l.address,
            'timezone', l.timezone, 'is_online', l.is_online, 'meeting_url', l.meeting_url
        ) ORDER BY l.id)
        FROM locations l WHERE l.master_id = m.id AND l.is_active = TRUE
    ), '[]'::json) AS locations_json,

    COALESCE((
        SELECT json_agg(json_build_object(
            'id', s.id, 'name', s.name, 'slug', s.slug,
            'price', s.price, 'duration_mins', s.duration_mins
        ) ORDER BY s.price ASC)
        FROM (
            SELECT id, name, slug, price, duration_mins
            FROM services
            WHERE master_id = m.id AND is_active = TRUE
            ORDER BY price ASC
            LIMIT 3
        ) s
    ), '[]'::json) AS top_services_json,

    (SELECT COUNT(*) FROM services
     WHERE master_id = m.id AND is_active = TRUE) AS total_services

FROM masters m
JOIN users u ON u.id = m.user_id
WHERE m.is_accepting_bookings = TRUE
  AND ($1::int      IS NULL OR m.min_price >= $1)
  AND ($2::int      IS NULL OR m.min_price <= $2)
  AND ($3::int IS NULL OR m.years_of_experience >= $3)
  AND ($4::text IS NULL OR m.specialization = $4)
  AND ($5::text IS NULL OR u.timezone = $5)
  AND ($6::int IS NULL OR EXISTS (
        SELECT 1 FROM services s
        WHERE s.master_id = m.id AND s.id = $6 AND s.is_active = TRUE
  ))
  AND ($7::numeric IS NULL
       OR (m.avg_rating, m.id) < ($7, $8))
ORDER BY m.avg_rating DESC, m.id DESC
LIMIT $9
`

type ListMastersByRatingParams struct {
	MinPrice       pgtype.Int4    `json:"min_price"`
	MaxPrice       pgtype.Int4    `json:"max_price"`
	MinExperience  pgtype.Int4    `json:"min_experience"`
	Specialization pgtype.Text    `json:"specialization"`
	MasterTimezone pgtype.Text    `json:"master_timezone"`
	ServiceID      pgtype.Int4    `json:"service_id"`
	CursorRating   pgtype.Numeric `json:"cursor_rating"`
	CursorID       pgtype.Numeric `json:"cursor_id"`
	PageSize       int32          `json:"page_size"`
}

type ListMastersByRatingRow struct {
	ID                  int32              `json:"id"`
	UserID              int32              `json:"user_id"`
	Slug                string             `json:"slug"`
	Bio                 pgtype.Text        `json:"bio"`
	Specialization      string             `json:"specialization"`
	YearsOfExperience   int32              `json:"years_of_experience"`
	IsAcceptingBookings pgtype.Bool        `json:"is_accepting_bookings"`
	DefaultLocationID   pgtype.Int4        `json:"default_location_id"`
	MinPrice            pgtype.Int4        `json:"min_price"`
	AvgRating           pgtype.Numeric     `json:"avg_rating"`
	ReviewsCount        pgtype.Int4        `json:"reviews_count"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	UserName            pgtype.Text        `json:"user_name"`
	UserEmail           string             `json:"user_email"`
	UserAvatarUrl       pgtype.Text        `json:"user_avatar_url"`
	UserTimezone        pgtype.Text        `json:"user_timezone"`
	UserEmailVerified   pgtype.Bool        `json:"user_email_verified"`
	UserRoleIds         []int32            `json:"user_role_ids"`
	LocationsJson       interface{}        `json:"locations_json"`
	TopServicesJson     interface{}        `json:"top_services_json"`
	TotalServices       int64              `json:"total_services"`
}

func (q *Queries) ListMastersByRating(ctx context.Context, arg ListMastersByRatingParams) ([]ListMastersByRatingRow, error) {
	rows, err := q.db.Query(ctx, listMastersByRating,
		arg.MinPrice,
		arg.MaxPrice,
		arg.MinExperience,
		arg.Specialization,
		arg.MasterTimezone,
		arg.ServiceID,
		arg.CursorRating,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMastersByRatingRow
	for rows.Next() {
		var i ListMastersByRatingRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.Bio,
			&i.Specialization,
			&i.YearsOfExperience,
			&i.IsAcceptingBookings,
			&i.DefaultLocationID,
			&i.MinPrice,
			&i.AvgRating,
			&i.ReviewsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
			&i.UserTimezone,
			&i.UserEmailVerified,
			&i.UserRoleIds,
			&i.LocationsJson,
			&i.TopServicesJson,
			&i.TotalServices,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const masterSlugExists = `-- name: MasterSlugExists :one
SELECT EXISTS(SELECT 1 FROM masters WHERE slug = $1) AS exists
`

func (q *Queries) MasterSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, masterSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const replaceMasterCertificates = `-- name: ReplaceMasterCertificates :exec
DELETE FROM certificates WHERE master_id = $1
`

func (q *Queries) ReplaceMasterCertificates(ctx context.Context, masterID int32) error {
	_, err := q.db.Exec(ctx, replaceMasterCertificates, masterID)
	return err
}

const replaceMasterLanguages = `-- name: ReplaceMasterLanguages :exec
DELETE FROM languages WHERE master_id = $1
`

func (q *Queries) ReplaceMasterLanguages(ctx context.Context, masterID int32) error {
	_, err := q.db.Exec(ctx, replaceMasterLanguages, masterID)
	return err
}

const setDefaultLocation = `-- name: SetDefaultLocation :exec
UPDATE masters SET default_location_id = $2, updated_at = NOW() WHERE id = $1
`

type SetDefaultLocationParams struct {
	ID                int32       `json:"id"`
	DefaultLocationID pgtype.Int4 `json:"default_location_id"`
}

func (q *Queries) SetDefaultLocation(ctx context.Context, arg SetDefaultLocationParams) error {
	_, err := q.db.Exec(ctx, setDefaultLocation, arg.ID, arg.DefaultLocationID)
	return err
}

const updateMaster = `-- name: UpdateMaster :one
UPDATE masters
SET bio                  = COALESCE($1, bio),
    specialization       = COALESCE($2, specialization),
    years_of_experience  = COALESCE($3, years_of_experience),
    is_accepting_bookings = COALESCE($4, is_accepting_bookings),
    updated_at = NOW()
WHERE id = $5
RETURNING id, user_id, slug, bio, specialization, years_of_experience,
          is_accepting_bookings, default_location_id, min_price, avg_rating, reviews_count,
          created_at, updated_at
`

type UpdateMasterParams struct {
	Bio                 pgtype.Text `json:"bio"`
	Specialization      pgtype.Text `json:"specialization"`
	YearsOfExperience   pgtype.Int4 `json:"years_of_experience"`
	IsAcceptingBookings pgtype.Bool `json:"is_accepting_bookings"`
	ID                  int32       `json:"id"`
}

func (q *Queries) UpdateMaster(ctx context.Context, arg UpdateMasterParams) (Master, error) {
	row := q.db.QueryRow(ctx, updateMaster,
		arg.Bio,
		arg.Specialization,
		arg.YearsOfExperience,
		arg.IsAcceptingBookings,
		arg.ID,
	)
	var i Master
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Bio,
		&i.Specialization,
		&i.YearsOfExperience,
		&i.IsAcceptingBookings,
		&i.DefaultLocationID,
		&i.MinPrice,
		&i.AvgRating,
		&i.ReviewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMasterMinPrice = `-- name: UpdateMasterMinPrice :exec
UPDATE masters SET min_price = (
    SELECT COALESCE(MIN(price), 0) FROM services
    WHERE master_id = $1 AND is_active = TRUE
), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateMasterMinPrice(ctx context.Context, masterID int32) error {
	_, err := q.db.Exec(ctx, updateMasterMinPrice, masterID)
	return err
}

const updateMasterRating = `-- name: UpdateMasterRating :exec
UPDATE masters SET
    avg_rating = (SELECT COALESCE(AVG(r.rating), 0)
                  FROM reviews r
                  WHERE r.target_id = masters.id AND r.target = 1 AND r.status = 1),
    reviews_count = (SELECT COUNT(*)
                     FROM reviews r
                     WHERE r.target_id = masters.id AND r.target = 1 AND r.status = 1),
    updated_at = NOW()
WHERE masters.id = $1
`

func (q *Queries) UpdateMasterRating(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateMasterRating, id)
	return err
}

const updateMasterSlug = `-- name: UpdateMasterSlug :one
UPDATE masters SET slug = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, slug, bio, specialization, years_of_experience,
          is_accepting_bookings, default_location_id, min_price, avg_rating, reviews_count,
          created_at, updated_at
`

type UpdateMasterSlugParams struct {
	ID   int32  `json:"id"`
	Slug string `json:"slug"`
}

func (q *Queries) UpdateMasterSlug(ctx context.Context, arg UpdateMasterSlugParams) (Master, error) {
	row := q.db.QueryRow(ctx, updateMasterSlug, arg.ID, arg.Slug)
	var i Master
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Bio,
		&i.Specialization,
		&i.YearsOfExperience,
		&i.IsAcceptingBookings,
		&i.DefaultLocationID,
		&i.MinPrice,
		&i.AvgRating,
		&i.ReviewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
