// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ProficiencyLevel string

const (
	ProficiencyLevelBeginner     ProficiencyLevel = "beginner"
	ProficiencyLevelIntermediate ProficiencyLevel = "intermediate"
	ProficiencyLevelAdvanced     ProficiencyLevel = "advanced"
)

func (e *ProficiencyLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProficiencyLevel(s)
	case string:
		*e = ProficiencyLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for ProficiencyLevel: %T", src)
	}
	return nil
}

type NullProficiencyLevel struct {
	ProficiencyLevel ProficiencyLevel `json:"proficiency_level"`
	Valid            bool             `json:"valid"` // Valid is true if ProficiencyLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProficiencyLevel) Scan(value interface{}) error {
	if value == nil {
		ns.ProficiencyLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProficiencyLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProficiencyLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProficiencyLevel), nil
}

type Appointment struct {
	ID              int64              `json:"id"`
	ClientID        int32              `json:"client_id"`
	CreatedBy       pgtype.Int4        `json:"created_by"`
	MasterID        int32              `json:"master_id"`
	ServiceID       int32              `json:"service_id"`
	LocationID      int32              `json:"location_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	Timezone        string             `json:"timezone"`
	Status          int16              `json:"status"`
	Price           int32              `json:"price"`
	Currency        string             `json:"currency"`
	PaymentStatus   int16              `json:"payment_status"`
	IsOnline        bool               `json:"is_online"`
	MeetingUrl      pgtype.Text        `json:"meeting_url"`
	ClientNotes     pgtype.Text        `json:"client_notes"`
	MasterNotes     pgtype.Text        `json:"master_notes"`
	CancelledAt     pgtype.Timestamptz `json:"cancelled_at"`
	CancelledByRole pgtype.Int2        `json:"cancelled_by_role"`
	CancelledBy     pgtype.Int4        `json:"cancelled_by"`
	CancelReason    pgtype.Text        `json:"cancel_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Certificate struct {
	ID           int32              `json:"id"`
	MasterID     int32              `json:"master_id"`
	Name         string             `json:"name"`
	Organization string             `json:"organization"`
	Year         int32              `json:"year"`
	FileUrl      string             `json:"file_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DefaultService struct {
	ID           int32              `json:"id"`
	CategoryID   int32              `json:"category_id"`
	Slug         string             `json:"slug"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Price        int32              `json:"price"`
	Currency     string             `json:"currency"`
	DurationMins int32              `json:"duration_mins"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Exception struct {
	ID          int32              `json:"id"`
	LocationID  int32              `json:"location_id"`
	Date        pgtype.Date        `json:"date"`
	Type        int16              `json:"type"`
	IsFullDay   bool               `json:"is_full_day"`
	CustomStart pgtype.Time        `json:"custom_start"`
	CustomEnd   pgtype.Time        `json:"custom_end"`
	RestStart   pgtype.Time        `json:"rest_start"`
	RestEnd     pgtype.Time        `json:"rest_end"`
	Reason      pgtype.Text        `json:"reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Language struct {
	ID          int32              `json:"id"`
	MasterID    int32              `json:"master_id"`
	Language    string             `json:"language"`
	Proficiency ProficiencyLevel   `json:"proficiency"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Location struct {
	ID         int32              `json:"id"`
	MasterID   int32              `json:"master_id"`
	Name       string             `json:"name"`
	Address    string             `json:"address"`
	Timezone   string             `json:"timezone"`
	IsOnline   pgtype.Bool        `json:"is_online"`
	MeetingUrl pgtype.Text        `json:"meeting_url"`
	IsActive   pgtype.Bool        `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Master struct {
	ID                  int32              `json:"id"`
	UserID              int32              `json:"user_id"`
	Slug                string             `json:"slug"`
	Bio                 pgtype.Text        `json:"bio"`
	Specialization      string             `json:"specialization"`
	YearsOfExperience   int32              `json:"years_of_experience"`
	IsAcceptingBookings pgtype.Bool        `json:"is_accepting_bookings"`
	DefaultLocationID   pgtype.Int4        `json:"default_location_id"`
	MinPrice            pgtype.Int4        `json:"min_price"`
	AvgRating           pgtype.Numeric     `json:"avg_rating"`
	ReviewsCount        pgtype.Int4        `json:"reviews_count"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Notification struct {
	ID        int64              `json:"id"`
	UserID    int32              `json:"user_id"`
	Type      int16              `json:"type"`
	Channel   int16              `json:"channel"`
	Status    int16              `json:"status"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Link      pgtype.Text        `json:"link"`
	Metadata  []byte             `json:"metadata"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NotificationSetting struct {
	UserID          int32              `json:"user_id"`
	EmailEnabled    bool               `json:"email_enabled"`
	TelegramEnabled bool               `json:"telegram_enabled"`
	SmsEnabled      bool               `json:"sms_enabled"`
	PushEnabled     bool               `json:"push_enabled"`
	MutedTypes      []int16            `json:"muted_types"`
	Reminder24h     bool               `json:"reminder_24h"`
	Reminder2h      bool               `json:"reminder_2h"`
	Reminder30m     bool               `json:"reminder_30m"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID            int64              `json:"id"`
	UserID        int32              `json:"user_id"`
	Amount        int32              `json:"amount"`
	Currency      string             `json:"currency"`
	Status        int16              `json:"status"`
	Provider      int16              `json:"provider"`
	Purpose       int16              `json:"purpose"`
	ReferenceID   string             `json:"reference_id"`
	ExternalID    pgtype.Text        `json:"external_id"`
	PaymentUrl    pgtype.Text        `json:"payment_url"`
	FailureReason pgtype.Text        `json:"failure_reason"`
	ReceiptUrl    pgtype.Text        `json:"receipt_url"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	RefundedAt    pgtype.Timestamptz `json:"refunded_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Review struct {
	ID          int64              `json:"id"`
	AuthorID    int32              `json:"author_id"`
	TargetID    int32              `json:"target_id"`
	Target      int16              `json:"target"`
	ReferenceID string             `json:"reference_id"`
	Rating      int16              `json:"rating"`
	Comment     pgtype.Text        `json:"comment"`
	Reply       pgtype.Text        `json:"reply"`
	RepliedAt   pgtype.Timestamptz `json:"replied_at"`
	Status      int16              `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ScheduleRule struct {
	ID                     int32              `json:"id"`
	LocationID             int32              `json:"location_id"`
	DayOfWeek              int16              `json:"day_of_week"`
	IsWorkingDay           bool               `json:"is_working_day"`
	WorkStart              pgtype.Time        `json:"work_start"`
	WorkEnd                pgtype.Time        `json:"work_end"`
	RestStart              pgtype.Time        `json:"rest_start"`
	RestEnd                pgtype.Time        `json:"rest_end"`
	BufferBetweenSlotsMins int32              `json:"buffer_between_slots_mins"`
	SlotStepMins           int32              `json:"slot_step_mins"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type Service struct {
	ID               int32              `json:"id"`
	MasterID         int32              `json:"master_id"`
	DefaultServiceID pgtype.Int4        `json:"default_service_id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Description      pgtype.Text        `json:"description"`
	Price            int32              `json:"price"`
	Currency         string             `json:"currency"`
	DurationMins     int32              `json:"duration_mins"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ServiceLocation struct {
	ServiceID    int32              `json:"service_id"`
	LocationID   int32              `json:"location_id"`
	DurationMins int32              `json:"duration_mins"`
	Price        int32              `json:"price"`
	Currency     string             `json:"currency"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            int32              `json:"id"`
	Name          pgtype.Text        `json:"name"`
	Email         string             `json:"email"`
	EmailVerified pgtype.Bool        `json:"email_verified"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	Timezone      pgtype.Text        `json:"timezone"`
	PasswordHash  string             `json:"password_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UserRole struct {
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}
