// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    user_id, type, channel, status, title, body, link, metadata, sent_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, type, channel, status, title, body, link,
          metadata, sent_at, read_at, created_at
`

type CreateNotificationParams struct {
	UserID   int32              `json:"user_id"`
	Type     int16              `json:"type"`
	Channel  int16              `json:"channel"`
	Status   int16              `json:"status"`
	Title    string             `json:"title"`
	Body     string             `json:"body"`
	Link     pgtype.Text        `json:"link"`
	Metadata []byte             `json:"metadata"`
	SentAt   pgtype.Timestamptz `json:"sent_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Channel,
		arg.Status,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.Metadata,
		arg.SentAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Channel,
		&i.Status,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.Metadata,
		&i.SentAt,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :execrows
DELETE FROM notifications
WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     int64 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT
    id, user_id, type, channel, status, title, body, link,
    metadata, sent_at, read_at, created_at
FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id int64) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Channel,
		&i.Status,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.Metadata,
		&i.SentAt,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingNotifications = `-- name: GetPendingNotifications :many
SELECT
    id, user_id, type, channel, status, title, body, link,
    metadata, sent_at, read_at, created_at
FROM notifications
WHERE status = 1
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingNotifications(ctx context.Context, limit int32) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getPendingNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Channel,
			&i.Status,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.Metadata,
			&i.SentAt,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*)::int AS count
FROM notifications
WHERE user_id = $1 AND status != 4
`

func (q *Queries) GetUnreadCount(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getUnreadCount, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const listMyNotifications = `-- name: ListMyNotifications :many
SELECT
    n.id, n.user_id, n.type, n.channel, n.status, n.title, n.body, n.link,
    n.metadata, n.sent_at, n.read_at, n.created_at,
    (SELECT COUNT(*)::int FROM notifications n2
     WHERE n2.user_id = $1 AND n2.status != 4) AS unread_count
FROM notifications n
WHERE n.user_id = $1
  AND ($2::smallint IS NULL OR n.status = $2)
  AND ($3::timestamptz IS NULL
       OR (n.created_at, n.id) < ($3, $4))
ORDER BY n.created_at DESC, n.id DESC
LIMIT $5
`

type ListMyNotificationsParams struct {
	UserID       int32              `json:"user_id"`
	StatusFilter pgtype.Int2        `json:"status_filter"`
	CursorTime   pgtype.Timestamptz `json:"cursor_time"`
	CursorID     pgtype.Timestamptz `json:"cursor_id"`
	PageSize     int32              `json:"page_size"`
}

type ListMyNotificationsRow struct {
	ID          int64              `json:"id"`
	UserID      int32              `json:"user_id"`
	Type        int16              `json:"type"`
	Channel     int16              `json:"channel"`
	Status      int16              `json:"status"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	Link        pgtype.Text        `json:"link"`
	Metadata    []byte             `json:"metadata"`
	SentAt      pgtype.Timestamptz `json:"sent_at"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UnreadCount int32              `json:"unread_count"`
}

func (q *Queries) ListMyNotifications(ctx context.Context, arg ListMyNotificationsParams) ([]ListMyNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listMyNotifications,
		arg.UserID,
		arg.StatusFilter,
		arg.CursorTime,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyNotificationsRow
	for rows.Next() {
		var i ListMyNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Channel,
			&i.Status,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.Metadata,
			&i.SentAt,
			&i.ReadAt,
			&i.CreatedAt,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNotificationsByType = `-- name: ListUserNotificationsByType :many
SELECT
    id, user_id, type, channel, status, title, body, link,
    metadata, sent_at, read_at, created_at
FROM notifications
WHERE user_id = $1 AND type = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListUserNotificationsByTypeParams struct {
	UserID int32 `json:"user_id"`
	Type   int16 `json:"type"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListUserNotificationsByType(ctx context.Context, arg ListUserNotificationsByTypeParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUserNotificationsByType, arg.UserID, arg.Type, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Channel,
			&i.Status,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.Metadata,
			&i.SentAt,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :execrows
UPDATE notifications
SET status  = 4,
    read_at = NOW()
WHERE user_id = $1 AND status != 4
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID int32) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsAsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :execrows
UPDATE notifications
SET status  = 4,
    read_at = NOW()
WHERE id = $1 AND user_id = $2 AND status != 4
`

type MarkNotificationAsReadParams struct {
	ID     int64 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE notifications
SET status = 3
WHERE id = $1 AND status = 1
`

func (q *Queries) MarkNotificationFailed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, id)
	return err
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notifications
SET status  = 2,
    sent_at = NOW()
WHERE id = $1 AND status = 1
`

func (q *Queries) MarkNotificationSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markNotificationSent, id)
	return err
}
