// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPayment = `-- name: CancelPayment :one
UPDATE payments
SET status     = 3,
    updated_at = NOW()
WHERE id = $1 AND status = 1
RETURNING id, user_id, amount, currency, status, provider, purpose,
          reference_id, external_id, payment_url,
          failure_reason, receipt_url,
          paid_at, refunded_at, expires_at,
          created_at, updated_at
`

func (q *Queries) CancelPayment(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, cancelPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.Purpose,
		&i.ReferenceID,
		&i.ExternalID,
		&i.PaymentUrl,
		&i.FailureReason,
		&i.ReceiptUrl,
		&i.PaidAt,
		&i.RefundedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    user_id, amount, currency, status, provider, purpose,
    reference_id, external_id, payment_url, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, amount, currency, status, provider, purpose,
          reference_id, external_id, payment_url,
          failure_reason, receipt_url,
          paid_at, refunded_at, expires_at,
          created_at, updated_at
`

type CreatePaymentParams struct {
	UserID      int32              `json:"user_id"`
	Amount      int32              `json:"amount"`
	Currency    string             `json:"currency"`
	Status      int16              `json:"status"`
	Provider    int16              `json:"provider"`
	Purpose     int16              `json:"purpose"`
	ReferenceID string             `json:"reference_id"`
	ExternalID  pgtype.Text        `json:"external_id"`
	PaymentUrl  pgtype.Text        `json:"payment_url"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.Provider,
		arg.Purpose,
		arg.ReferenceID,
		arg.ExternalID,
		arg.PaymentUrl,
		arg.ExpiresAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.Purpose,
		&i.ReferenceID,
		&i.ExternalID,
		&i.PaymentUrl,
		&i.FailureReason,
		&i.ReceiptUrl,
		&i.PaidAt,
		&i.RefundedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expirePendingPayments = `-- name: ExpirePendingPayments :execrows
UPDATE payments
SET status = 5, updated_at = NOW()
WHERE status = 1 AND expires_at < NOW()
`

func (q *Queries) ExpirePendingPayments(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expirePendingPayments)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPaidPaymentByReference = `-- name: GetPaidPaymentByReference :one
SELECT
    id, user_id, amount, currency, status, provider, purpose,
    reference_id, external_id, payment_url,
    failure_reason, receipt_url,
    paid_at, refunded_at, expires_at,
    created_at, updated_at
FROM payments
WHERE purpose = $1
  AND reference_id = $2
  AND status = 2
ORDER BY paid_at DESC
LIMIT 1
`

type GetPaidPaymentByReferenceParams struct {
	Purpose     int16  `json:"purpose"`
	ReferenceID string `json:"reference_id"`
}

func (q *Queries) GetPaidPaymentByReference(ctx context.Context, arg GetPaidPaymentByReferenceParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaidPaymentByReference, arg.Purpose, arg.ReferenceID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.Purpose,
		&i.ReferenceID,
		&i.ExternalID,
		&i.PaymentUrl,
		&i.FailureReason,
		&i.ReceiptUrl,
		&i.PaidAt,
		&i.RefundedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByExternalID = `-- name: GetPaymentByExternalID :one
SELECT
    p.id, p.user_id, p.amount, p.currency, p.status, p.provider, p.purpose,
    p.reference_id, p.external_id, p.payment_url,
    p.failure_reason, p.receipt_url,
    p.paid_at, p.refunded_at, p.expires_at,
    p.created_at, p.updated_at,

    u.name       AS user_name,
    u.email      AS user_email,
    u.avatar_url AS user_avatar_url
FROM payments p
JOIN users u ON u.id = p.user_id
WHERE p.provider = $1 AND p.external_id = $2
`

type GetPaymentByExternalIDParams struct {
	Provider   int16       `json:"provider"`
	ExternalID pgtype.Text `json:"external_id"`
}

type GetPaymentByExternalIDRow struct {
	ID            int64              `json:"id"`
	UserID        int32              `json:"user_id"`
	Amount        int32              `json:"amount"`
	Currency      string             `json:"currency"`
	Status        int16              `json:"status"`
	Provider      int16              `json:"provider"`
	Purpose       int16              `json:"purpose"`
	ReferenceID   string             `json:"reference_id"`
	ExternalID    pgtype.Text        `json:"external_id"`
	PaymentUrl    pgtype.Text        `json:"payment_url"`
	FailureReason pgtype.Text        `json:"failure_reason"`
	ReceiptUrl    pgtype.Text        `json:"receipt_url"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	RefundedAt    pgtype.Timestamptz `json:"refunded_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	UserName      pgtype.Text        `json:"user_name"`
	UserEmail     string             `json:"user_email"`
	UserAvatarUrl pgtype.Text        `json:"user_avatar_url"`
}

func (q *Queries) GetPaymentByExternalID(ctx context.Context, arg GetPaymentByExternalIDParams) (GetPaymentByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByExternalID, arg.Provider, arg.ExternalID)
	var i GetPaymentByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.Purpose,
		&i.ReferenceID,
		&i.ExternalID,
		&i.PaymentUrl,
		&i.FailureReason,
		&i.ReceiptUrl,
		&i.PaidAt,
		&i.RefundedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
		&i.UserAvatarUrl,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT
    p.id, p.user_id, p.amount, p.currency, p.status, p.provider, p.purpose,
    p.reference_id, p.external_id, p.payment_url,
    p.failure_reason, p.receipt_url,
    p.paid_at, p.refunded_at, p.expires_at,
    p.created_at, p.updated_at,

    u.name       AS user_name,
    u.email      AS user_email,
    u.avatar_url AS user_avatar_url
FROM payments p
JOIN users u ON u.id = p.user_id
WHERE p.id = $1
`

type GetPaymentByIDRow struct {
	ID            int64              `json:"id"`
	UserID        int32              `json:"user_id"`
	Amount        int32              `json:"amount"`
	Currency      string             `json:"currency"`
	Status        int16              `json:"status"`
	Provider      int16              `json:"provider"`
	Purpose       int16              `json:"purpose"`
	ReferenceID   string             `json:"reference_id"`
	ExternalID    pgtype.Text        `json:"external_id"`
	PaymentUrl    pgtype.Text        `json:"payment_url"`
	FailureReason pgtype.Text        `json:"failure_reason"`
	ReceiptUrl    pgtype.Text        `json:"receipt_url"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	RefundedAt    pgtype.Timestamptz `json:"refunded_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	UserName      pgtype.Text        `json:"user_name"`
	UserEmail     string             `json:"user_email"`
	UserAvatarUrl pgtype.Text        `json:"user_avatar_url"`
}

func (q *Queries) GetPaymentByID(ctx context.Context, id int64) (GetPaymentByIDRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i GetPaymentByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.Purpose,
		&i.ReferenceID,
		&i.ExternalID,
		&i.PaymentUrl,
		&i.FailureReason,
		&i.ReceiptUrl,
		&i.PaidAt,
		&i.RefundedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
		&i.UserAvatarUrl,
	)
	return i, err
}

const getPaymentByReference = `-- name: GetPaymentByReference :one
SELECT
    p.id, p.user_id, p.amount, p.currency, p.status, p.provider, p.purpose,
    p.reference_id, p.external_id, p.payment_url,
    p.failure_reason, p.receipt_url,
    p.paid_at, p.refunded_at, p.expires_at,
    p.created_at, p.updated_at,

    u.name       AS user_name,
    u.email      AS user_email,
    u.avatar_url AS user_avatar_url
FROM payments p
JOIN users u ON u.id = p.user_id
WHERE p.purpose = $1 AND p.reference_id = $2
ORDER BY p.created_at DESC
LIMIT 1
`

type GetPaymentByReferenceParams struct {
	Purpose     int16  `json:"purpose"`
	ReferenceID string `json:"reference_id"`
}

type GetPaymentByReferenceRow struct {
	ID            int64              `json:"id"`
	UserID        int32              `json:"user_id"`
	Amount        int32              `json:"amount"`
	Currency      string             `json:"currency"`
	Status        int16              `json:"status"`
	Provider      int16              `json:"provider"`
	Purpose       int16              `json:"purpose"`
	ReferenceID   string             `json:"reference_id"`
	ExternalID    pgtype.Text        `json:"external_id"`
	PaymentUrl    pgtype.Text        `json:"payment_url"`
	FailureReason pgtype.Text        `json:"failure_reason"`
	ReceiptUrl    pgtype.Text        `json:"receipt_url"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	RefundedAt    pgtype.Timestamptz `json:"refunded_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	UserName      pgtype.Text        `json:"user_name"`
	UserEmail     string             `json:"user_email"`
	UserAvatarUrl pgtype.Text        `json:"user_avatar_url"`
}

func (q *Queries) GetPaymentByReference(ctx context.Context, arg GetPaymentByReferenceParams) (GetPaymentByReferenceRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByReference, arg.Purpose, arg.ReferenceID)
	var i GetPaymentByReferenceRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.Purpose,
		&i.ReferenceID,
		&i.ExternalID,
		&i.PaymentUrl,
		&i.FailureReason,
		&i.ReceiptUrl,
		&i.PaidAt,
		&i.RefundedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
		&i.UserAvatarUrl,
	)
	return i, err
}

const listAllPayments = `-- name: ListAllPayments :many
SELECT
    p.id, p.user_id, p.amount, p.currency, p.status, p.provider, p.purpose,
    p.reference_id, p.external_id, p.payment_url,
    p.failure_reason, p.receipt_url,
    p.paid_at, p.refunded_at, p.expires_at,
    p.created_at, p.updated_at,

    u.name       AS user_name,
    u.email      AS user_email,
    u.avatar_url AS user_avatar_url
FROM payments p
JOIN users u ON u.id = p.user_id
WHERE ($1::smallint   IS NULL OR p.status = $1)
  AND ($2::int              IS NULL OR p.user_id = $2)
  AND ($3::timestamptz    IS NULL OR p.created_at >= $3)
  AND ($4::timestamptz      IS NULL OR p.created_at <  $4)
  AND ($5::timestamptz  IS NULL
       OR (p.created_at, p.id) < ($5, $6))
ORDER BY p.created_at DESC, p.id DESC
LIMIT $7
`

type ListAllPaymentsParams struct {
	StatusFilter pgtype.Int2        `json:"status_filter"`
	UserID       pgtype.Int4        `json:"user_id"`
	FromTime     pgtype.Timestamptz `json:"from_time"`
	ToTime       pgtype.Timestamptz `json:"to_time"`
	CursorTime   pgtype.Timestamptz `json:"cursor_time"`
	CursorID     pgtype.Timestamptz `json:"cursor_id"`
	PageSize     int32              `json:"page_size"`
}

type ListAllPaymentsRow struct {
	ID            int64              `json:"id"`
	UserID        int32              `json:"user_id"`
	Amount        int32              `json:"amount"`
	Currency      string             `json:"currency"`
	Status        int16              `json:"status"`
	Provider      int16              `json:"provider"`
	Purpose       int16              `json:"purpose"`
	ReferenceID   string             `json:"reference_id"`
	ExternalID    pgtype.Text        `json:"external_id"`
	PaymentUrl    pgtype.Text        `json:"payment_url"`
	FailureReason pgtype.Text        `json:"failure_reason"`
	ReceiptUrl    pgtype.Text        `json:"receipt_url"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	RefundedAt    pgtype.Timestamptz `json:"refunded_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	UserName      pgtype.Text        `json:"user_name"`
	UserEmail     string             `json:"user_email"`
	UserAvatarUrl pgtype.Text        `json:"user_avatar_url"`
}

func (q *Queries) ListAllPayments(ctx context.Context, arg ListAllPaymentsParams) ([]ListAllPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listAllPayments,
		arg.StatusFilter,
		arg.UserID,
		arg.FromTime,
		arg.ToTime,
		arg.CursorTime,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPaymentsRow
	for rows.Next() {
		var i ListAllPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Provider,
			&i.Purpose,
			&i.ReferenceID,
			&i.ExternalID,
			&i.PaymentUrl,
			&i.FailureReason,
			&i.ReceiptUrl,
			&i.PaidAt,
			&i.RefundedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyPayments = `-- name: ListMyPayments :many
SELECT
    p.id, p.user_id, p.amount, p.currency, p.status, p.provider, p.purpose,
    p.reference_id, p.external_id, p.payment_url,
    p.failure_reason, p.receipt_url,
    p.paid_at, p.refunded_at, p.expires_at,
    p.created_at, p.updated_at,

    u.name       AS user_name,
    u.email      AS user_email,
    u.avatar_url AS user_avatar_url
FROM payments p
JOIN users u ON u.id = p.user_id
WHERE p.user_id = $1
  AND ($2::smallint  IS NULL OR p.status  = $2)
  AND ($3::smallint IS NULL OR p.purpose = $3)
  AND ($4::timestamptz IS NULL
       OR (p.created_at, p.id) < ($4, $5))
ORDER BY p.created_at DESC, p.id DESC
LIMIT $6
`

type ListMyPaymentsParams struct {
	UserID        int32              `json:"user_id"`
	StatusFilter  pgtype.Int2        `json:"status_filter"`
	PurposeFilter pgtype.Int2        `json:"purpose_filter"`
	CursorTime    pgtype.Timestamptz `json:"cursor_time"`
	CursorID      pgtype.Timestamptz `json:"cursor_id"`
	PageSize      int32              `json:"page_size"`
}

type ListMyPaymentsRow struct {
	ID            int64              `json:"id"`
	UserID        int32              `json:"user_id"`
	Amount        int32              `json:"amount"`
	Currency      string             `json:"currency"`
	Status        int16              `json:"status"`
	Provider      int16              `json:"provider"`
	Purpose       int16              `json:"purpose"`
	ReferenceID   string             `json:"reference_id"`
	ExternalID    pgtype.Text        `json:"external_id"`
	PaymentUrl    pgtype.Text        `json:"payment_url"`
	FailureReason pgtype.Text        `json:"failure_reason"`
	ReceiptUrl    pgtype.Text        `json:"receipt_url"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	RefundedAt    pgtype.Timestamptz `json:"refunded_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	UserName      pgtype.Text        `json:"user_name"`
	UserEmail     string             `json:"user_email"`
	UserAvatarUrl pgtype.Text        `json:"user_avatar_url"`
}

func (q *Queries) ListMyPayments(ctx context.Context, arg ListMyPaymentsParams) ([]ListMyPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listMyPayments,
		arg.UserID,
		arg.StatusFilter,
		arg.PurposeFilter,
		arg.CursorTime,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyPaymentsRow
	for rows.Next() {
		var i ListMyPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Provider,
			&i.Purpose,
			&i.ReferenceID,
			&i.ExternalID,
			&i.PaymentUrl,
			&i.FailureReason,
			&i.ReceiptUrl,
			&i.PaidAt,
			&i.RefundedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentFailed = `-- name: MarkPaymentFailed :one
UPDATE payments
SET status         = 3,
    failure_reason = $2,
    updated_at     = NOW()
WHERE id = $1 AND status = 1
RETURNING id, user_id, amount, currency, status, provider, purpose,
          reference_id, external_id, payment_url,
          failure_reason, receipt_url,
          paid_at, refunded_at, expires_at,
          created_at, updated_at
`

type MarkPaymentFailedParams struct {
	ID            int64       `json:"id"`
	FailureReason pgtype.Text `json:"failure_reason"`
}

func (q *Queries) MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentFailed, arg.ID, arg.FailureReason)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.Purpose,
		&i.ReferenceID,
		&i.ExternalID,
		&i.PaymentUrl,
		&i.FailureReason,
		&i.ReceiptUrl,
		&i.PaidAt,
		&i.RefundedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentPaid = `-- name: MarkPaymentPaid :one
UPDATE payments
SET status       = 2,
    paid_at      = NOW(),
    external_id  = COALESCE($2, external_id),
    receipt_url  = COALESCE($3, receipt_url),
    payment_url  = COALESCE($4, payment_url),
    updated_at   = NOW()
WHERE id = $1 AND status = 1
RETURNING id, user_id, amount, currency, status, provider, purpose,
          reference_id, external_id, payment_url,
          failure_reason, receipt_url,
          paid_at, refunded_at, expires_at,
          created_at, updated_at
`

type MarkPaymentPaidParams struct {
	ID         int64       `json:"id"`
	ExternalID pgtype.Text `json:"external_id"`
	ReceiptUrl pgtype.Text `json:"receipt_url"`
	PaymentUrl pgtype.Text `json:"payment_url"`
}

func (q *Queries) MarkPaymentPaid(ctx context.Context, arg MarkPaymentPaidParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentPaid,
		arg.ID,
		arg.ExternalID,
		arg.ReceiptUrl,
		arg.PaymentUrl,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.Purpose,
		&i.ReferenceID,
		&i.ExternalID,
		&i.PaymentUrl,
		&i.FailureReason,
		&i.ReceiptUrl,
		&i.PaidAt,
		&i.RefundedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentRefunded = `-- name: MarkPaymentRefunded :one
UPDATE payments
SET status       = 4,
    refunded_at  = NOW(),
    updated_at   = NOW()
WHERE id = $1 AND status = 2
RETURNING id, user_id, amount, currency, status, provider, purpose,
          reference_id, external_id, payment_url,
          failure_reason, receipt_url,
          paid_at, refunded_at, expires_at,
          created_at, updated_at
`

func (q *Queries) MarkPaymentRefunded(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentRefunded, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.Purpose,
		&i.ReferenceID,
		&i.ExternalID,
		&i.PaymentUrl,
		&i.FailureReason,
		&i.ReceiptUrl,
		&i.PaidAt,
		&i.RefundedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentBelongsToUser = `-- name: PaymentBelongsToUser :one
SELECT EXISTS(
    SELECT 1 FROM payments WHERE id = $1 AND user_id = $2
) AS belongs
`

type PaymentBelongsToUserParams struct {
	ID     int64 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) PaymentBelongsToUser(ctx context.Context, arg PaymentBelongsToUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, paymentBelongsToUser, arg.ID, arg.UserID)
	var belongs bool
	err := row.Scan(&belongs)
	return belongs, err
}

const paymentStatusByID = `-- name: PaymentStatusByID :one
SELECT status FROM payments WHERE id = $1
`

func (q *Queries) PaymentStatusByID(ctx context.Context, id int64) (int16, error) {
	row := q.db.QueryRow(ctx, paymentStatusByID, id)
	var status int16
	err := row.Scan(&status)
	return status, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, amount, currency, status, provider, purpose,
          reference_id, external_id, payment_url,
          failure_reason, receipt_url,
          paid_at, refunded_at, expires_at,
          created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID     int64 `json:"id"`
	Status int16 `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.Purpose,
		&i.ReferenceID,
		&i.ExternalID,
		&i.PaymentUrl,
		&i.FailureReason,
		&i.ReceiptUrl,
		&i.PaidAt,
		&i.RefundedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
