// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddUserRoles(ctx context.Context, arg AddUserRolesParams) error
	AppointmentBelongsToClient(ctx context.Context, arg AppointmentBelongsToClientParams) (bool, error)
	AppointmentBelongsToMaster(ctx context.Context, arg AppointmentBelongsToMasterParams) (bool, error)
	// ============================================================
	// ROLES
	// ============================================================
	AssignRole(ctx context.Context, arg AssignRoleParams) error
	CancelAppointment(ctx context.Context, arg CancelAppointmentParams) (CancelAppointmentRow, error)
	CancelPayment(ctx context.Context, id int64) (Payment, error)
	CategoryHasServices(ctx context.Context, categoryID int32) (bool, error)
	CompleteAppointment(ctx context.Context, arg CompleteAppointmentParams) (CompleteAppointmentRow, error)
	ConfirmAppointment(ctx context.Context, id int64) (ConfirmAppointmentRow, error)
	CountActiveLocationsByMaster(ctx context.Context, masterID int32) (int64, error)
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (CreateAppointmentRow, error)
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateDefaultNotificationSettings(ctx context.Context, userID int32) (NotificationSetting, error)
	CreateDefaultService(ctx context.Context, arg CreateDefaultServiceParams) (DefaultService, error)
	CreateException(ctx context.Context, arg CreateExceptionParams) (Exception, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateMaster(ctx context.Context, arg CreateMasterParams) (Master, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	// ============================================================
	// USERS
	// ============================================================
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DefaultServiceSlugExists(ctx context.Context, arg DefaultServiceSlugExistsParams) (bool, error)
	DeleteCategory(ctx context.Context, id int32) error
	DeleteDefaultService(ctx context.Context, id int32) error
	DeleteException(ctx context.Context, id int32) error
	DeleteExceptionByLocationAndDate(ctx context.Context, arg DeleteExceptionByLocationAndDateParams) error
	DeleteLocation(ctx context.Context, id int32) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) (int64, error)
	DeleteReview(ctx context.Context, arg DeleteReviewParams) (DeleteReviewRow, error)
	DeleteScheduleRulesByLocation(ctx context.Context, locationID int32) error
	DeleteService(ctx context.Context, arg DeleteServiceParams) error
	DeleteUser(ctx context.Context, id int32) error
	ExceptionBelongsToLocation(ctx context.Context, arg ExceptionBelongsToLocationParams) (bool, error)
	ExpirePendingPayments(ctx context.Context) (int64, error)
	GetAppointmentByID(ctx context.Context, id int64) (GetAppointmentByIDRow, error)
	GetAverageRatingByTarget(ctx context.Context, arg GetAverageRatingByTargetParams) (GetAverageRatingByTargetRow, error)
	GetBookedSlotsForDay(ctx context.Context, arg GetBookedSlotsForDayParams) ([]GetBookedSlotsForDayRow, error)
	GetBookedSlotsInRange(ctx context.Context, arg GetBookedSlotsInRangeParams) ([]GetBookedSlotsInRangeRow, error)
	GetCategory(ctx context.Context, id int32) (Category, error)
	GetChannelEnabled(ctx context.Context, userID int32) (GetChannelEnabledRow, error)
	GetDefaultService(ctx context.Context, id int32) (DefaultService, error)
	GetDefaultServiceForCopy(ctx context.Context, id int32) (GetDefaultServiceForCopyRow, error)
	GetExceptionByLocationAndDate(ctx context.Context, arg GetExceptionByLocationAndDateParams) (Exception, error)
	GetExceptionsByLocationAndRange(ctx context.Context, arg GetExceptionsByLocationAndRangeParams) ([]Exception, error)
	GetLocationByID(ctx context.Context, id int32) (Location, error)
	GetLocationsByService(ctx context.Context, serviceID int32) ([]GetLocationsByServiceRow, error)
	GetMasterBySlug(ctx context.Context, slug string) (GetMasterBySlugRow, error)
	GetMasterByUserID(ctx context.Context, userID int32) (GetMasterByUserIDRow, error)
	GetMasterCertificates(ctx context.Context, masterID int32) ([]GetMasterCertificatesRow, error)
	GetMasterIDByUserID(ctx context.Context, userID int32) (int32, error)
	GetMasterLanguages(ctx context.Context, masterID int32) ([]GetMasterLanguagesRow, error)
	GetMyServices(ctx context.Context, masterID int32) ([]GetMyServicesRow, error)
	GetNotificationByID(ctx context.Context, id int64) (Notification, error)
	GetNotificationSettings(ctx context.Context, userID int32) (NotificationSetting, error)
	GetPaidPaymentByReference(ctx context.Context, arg GetPaidPaymentByReferenceParams) (Payment, error)
	GetPaymentByExternalID(ctx context.Context, arg GetPaymentByExternalIDParams) (GetPaymentByExternalIDRow, error)
	GetPaymentByID(ctx context.Context, id int64) (GetPaymentByIDRow, error)
	GetPaymentByReference(ctx context.Context, arg GetPaymentByReferenceParams) (GetPaymentByReferenceRow, error)
	GetPendingNotifications(ctx context.Context, limit int32) ([]Notification, error)
	GetReviewByID(ctx context.Context, id int64) (GetReviewByIDRow, error)
	GetReviewByReference(ctx context.Context, arg GetReviewByReferenceParams) (GetReviewByReferenceRow, error)
	GetReviewSummary(ctx context.Context, arg GetReviewSummaryParams) (GetReviewSummaryRow, error)
	GetScheduleRuleByLocationAndDay(ctx context.Context, arg GetScheduleRuleByLocationAndDayParams) (ScheduleRule, error)
	GetScheduleRulesByLocation(ctx context.Context, locationID int32) ([]ScheduleRule, error)
	GetServiceByID(ctx context.Context, id int32) (GetServiceByIDRow, error)
	GetUnreadCount(ctx context.Context, userID int32) (int32, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error)
	GetUserRoles(ctx context.Context, userID int32) ([]int32, error)
	HasRole(ctx context.Context, arg HasRoleParams) (bool, error)
	HideReview(ctx context.Context, id int64) (Review, error)
	InsertMasterCertificates(ctx context.Context, arg InsertMasterCertificatesParams) error
	InsertMasterLanguages(ctx context.Context, arg InsertMasterLanguagesParams) error
	InsertScheduleRule(ctx context.Context, arg InsertScheduleRuleParams) (ScheduleRule, error)
	InsertServiceLocations(ctx context.Context, arg InsertServiceLocationsParams) error
	IsTypeMuted(ctx context.Context, arg IsTypeMutedParams) (bool, error)
	ListAllPayments(ctx context.Context, arg ListAllPaymentsParams) ([]ListAllPaymentsRow, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListDefaultServices(ctx context.Context, categoryID pgtype.Int4) ([]DefaultService, error)
	ListLocationsByMaster(ctx context.Context, arg ListLocationsByMasterParams) ([]Location, error)
	ListMasterAppointmentsByRange(ctx context.Context, arg ListMasterAppointmentsByRangeParams) ([]ListMasterAppointmentsByRangeRow, error)
	ListMastersByExperience(ctx context.Context, arg ListMastersByExperienceParams) ([]ListMastersByExperienceRow, error)
	ListMastersByPrice(ctx context.Context, arg ListMastersByPriceParams) ([]ListMastersByPriceRow, error)
	ListMastersByRating(ctx context.Context, arg ListMastersByRatingParams) ([]ListMastersByRatingRow, error)
	ListMyAppointmentsByStatus(ctx context.Context, arg ListMyAppointmentsByStatusParams) ([]ListMyAppointmentsByStatusRow, error)
	ListMyAppointmentsUpcoming(ctx context.Context, arg ListMyAppointmentsUpcomingParams) ([]ListMyAppointmentsUpcomingRow, error)
	ListMyNotifications(ctx context.Context, arg ListMyNotificationsParams) ([]ListMyNotificationsRow, error)
	ListMyPayments(ctx context.Context, arg ListMyPaymentsParams) ([]ListMyPaymentsRow, error)
	ListMyReviews(ctx context.Context, arg ListMyReviewsParams) ([]ListMyReviewsRow, error)
	ListMyTargetReviews(ctx context.Context, arg ListMyTargetReviewsParams) ([]ListMyTargetReviewsRow, error)
	ListTargetReviews(ctx context.Context, arg ListTargetReviewsParams) ([]ListTargetReviewsRow, error)
	ListUserNotificationsByType(ctx context.Context, arg ListUserNotificationsByTypeParams) ([]Notification, error)
	LocationBelongsToMaster(ctx context.Context, arg LocationBelongsToMasterParams) (bool, error)
	MarkAllNotificationsAsRead(ctx context.Context, userID int32) (int64, error)
	MarkAppointmentNoShow(ctx context.Context, id int64) (MarkAppointmentNoShowRow, error)
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (int64, error)
	MarkNotificationFailed(ctx context.Context, id int64) error
	MarkNotificationSent(ctx context.Context, id int64) error
	MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (Payment, error)
	MarkPaymentPaid(ctx context.Context, arg MarkPaymentPaidParams) (Payment, error)
	MarkPaymentRefunded(ctx context.Context, id int64) (Payment, error)
	MasterSlugExists(ctx context.Context, slug string) (bool, error)
	PaymentBelongsToUser(ctx context.Context, arg PaymentBelongsToUserParams) (bool, error)
	PaymentStatusByID(ctx context.Context, id int64) (int16, error)
	RemoveRole(ctx context.Context, arg RemoveRoleParams) error
	ReplaceMasterCertificates(ctx context.Context, masterID int32) error
	ReplaceMasterLanguages(ctx context.Context, masterID int32) error
	ReplaceServiceLocations(ctx context.Context, serviceID int32) error
	ReplyToReview(ctx context.Context, arg ReplyToReviewParams) (Review, error)
	RescheduleAppointment(ctx context.Context, arg RescheduleAppointmentParams) (RescheduleAppointmentRow, error)
	ReviewBelongsToAuthor(ctx context.Context, arg ReviewBelongsToAuthorParams) (bool, error)
	ReviewExistsForReference(ctx context.Context, arg ReviewExistsForReferenceParams) (bool, error)
	ServiceSlugExists(ctx context.Context, arg ServiceSlugExistsParams) (bool, error)
	SetDefaultLocation(ctx context.Context, arg SetDefaultLocationParams) error
	SetEmailVerified(ctx context.Context, id int32) error
	SetUserRoles(ctx context.Context, userID int32) error
	UnhideReview(ctx context.Context, id int64) (Review, error)
	UpdateAppointmentPaymentStatus(ctx context.Context, arg UpdateAppointmentPaymentStatusParams) error
	UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) (UpdateAppointmentStatusRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateDefaultService(ctx context.Context, arg UpdateDefaultServiceParams) (DefaultService, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateMaster(ctx context.Context, arg UpdateMasterParams) (Master, error)
	UpdateMasterMinPrice(ctx context.Context, masterID int32) error
	UpdateMasterRating(ctx context.Context, id int32) error
	UpdateMasterSlug(ctx context.Context, arg UpdateMasterSlugParams) (Master, error)
	UpdateNotificationSettings(ctx context.Context, arg UpdateNotificationSettingsParams) (NotificationSetting, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	UpdateServicesMinPrice(ctx context.Context, masterID int32) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpsertScheduleRule(ctx context.Context, arg UpsertScheduleRuleParams) (ScheduleRule, error)
	ValidateLocationsBelongToMaster(ctx context.Context, arg ValidateLocationsBelongToMasterParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
