// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (author_id, target_id, target, reference_id, rating, comment)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, author_id, target_id, target, reference_id,
          rating, comment, reply, replied_at, status,
          created_at, updated_at
`

type CreateReviewParams struct {
	AuthorID    int32       `json:"author_id"`
	TargetID    int32       `json:"target_id"`
	Target      int16       `json:"target"`
	ReferenceID string      `json:"reference_id"`
	Rating      int16       `json:"rating"`
	Comment     pgtype.Text `json:"comment"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.AuthorID,
		arg.TargetID,
		arg.Target,
		arg.ReferenceID,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.TargetID,
		&i.Target,
		&i.ReferenceID,
		&i.Rating,
		&i.Comment,
		&i.Reply,
		&i.RepliedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :one
UPDATE reviews
SET status     = 3,
    updated_at = NOW()
WHERE id = $1 AND author_id = $2
RETURNING id, status
`

type DeleteReviewParams struct {
	ID       int64 `json:"id"`
	AuthorID int32 `json:"author_id"`
}

type DeleteReviewRow struct {
	ID     int64 `json:"id"`
	Status int16 `json:"status"`
}

func (q *Queries) DeleteReview(ctx context.Context, arg DeleteReviewParams) (DeleteReviewRow, error) {
	row := q.db.QueryRow(ctx, deleteReview, arg.ID, arg.AuthorID)
	var i DeleteReviewRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getAverageRatingByTarget = `-- name: GetAverageRatingByTarget :one
SELECT
    COALESCE(AVG(rating) FILTER (WHERE status = 1), 0)::float AS avg_rating,
    COUNT(*) FILTER (WHERE status = 1)::int                   AS total_reviews
FROM reviews
WHERE target = $1 AND target_id = $2
`

type GetAverageRatingByTargetParams struct {
	Target   int16 `json:"target"`
	TargetID int32 `json:"target_id"`
}

type GetAverageRatingByTargetRow struct {
	AvgRating    float64 `json:"avg_rating"`
	TotalReviews int32   `json:"total_reviews"`
}

func (q *Queries) GetAverageRatingByTarget(ctx context.Context, arg GetAverageRatingByTargetParams) (GetAverageRatingByTargetRow, error) {
	row := q.db.QueryRow(ctx, getAverageRatingByTarget, arg.Target, arg.TargetID)
	var i GetAverageRatingByTargetRow
	err := row.Scan(&i.AvgRating, &i.TotalReviews)
	return i, err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT
    r.id, r.author_id, r.target_id, r.target, r.reference_id,
    r.rating, r.comment, r.reply, r.replied_at, r.status,
    r.created_at, r.updated_at,

    u.name       AS author_name,
    u.avatar_url AS author_avatar
FROM reviews r
JOIN users u ON u.id = r.author_id
WHERE r.id = $1
`

type GetReviewByIDRow struct {
	ID           int64              `json:"id"`
	AuthorID     int32              `json:"author_id"`
	TargetID     int32              `json:"target_id"`
	Target       int16              `json:"target"`
	ReferenceID  string             `json:"reference_id"`
	Rating       int16              `json:"rating"`
	Comment      pgtype.Text        `json:"comment"`
	Reply        pgtype.Text        `json:"reply"`
	RepliedAt    pgtype.Timestamptz `json:"replied_at"`
	Status       int16              `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	AuthorName   pgtype.Text        `json:"author_name"`
	AuthorAvatar pgtype.Text        `json:"author_avatar"`
}

func (q *Queries) GetReviewByID(ctx context.Context, id int64) (GetReviewByIDRow, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i GetReviewByIDRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.TargetID,
		&i.Target,
		&i.ReferenceID,
		&i.Rating,
		&i.Comment,
		&i.Reply,
		&i.RepliedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
		&i.AuthorAvatar,
	)
	return i, err
}

const getReviewByReference = `-- name: GetReviewByReference :one
SELECT
    r.id, r.author_id, r.target_id, r.target, r.reference_id,
    r.rating, r.comment, r.reply, r.replied_at, r.status,
    r.created_at, r.updated_at,

    u.name       AS author_name,
    u.avatar_url AS author_avatar
FROM reviews r
JOIN users u ON u.id = r.author_id
WHERE r.author_id = $1 AND r.reference_id = $2
`

type GetReviewByReferenceParams struct {
	AuthorID    int32  `json:"author_id"`
	ReferenceID string `json:"reference_id"`
}

type GetReviewByReferenceRow struct {
	ID           int64              `json:"id"`
	AuthorID     int32              `json:"author_id"`
	TargetID     int32              `json:"target_id"`
	Target       int16              `json:"target"`
	ReferenceID  string             `json:"reference_id"`
	Rating       int16              `json:"rating"`
	Comment      pgtype.Text        `json:"comment"`
	Reply        pgtype.Text        `json:"reply"`
	RepliedAt    pgtype.Timestamptz `json:"replied_at"`
	Status       int16              `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	AuthorName   pgtype.Text        `json:"author_name"`
	AuthorAvatar pgtype.Text        `json:"author_avatar"`
}

func (q *Queries) GetReviewByReference(ctx context.Context, arg GetReviewByReferenceParams) (GetReviewByReferenceRow, error) {
	row := q.db.QueryRow(ctx, getReviewByReference, arg.AuthorID, arg.ReferenceID)
	var i GetReviewByReferenceRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.TargetID,
		&i.Target,
		&i.ReferenceID,
		&i.Rating,
		&i.Comment,
		&i.Reply,
		&i.RepliedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
		&i.AuthorAvatar,
	)
	return i, err
}

const getReviewSummary = `-- name: GetReviewSummary :one
SELECT
    $1::smallint AS target,
    $2::int   AS target_id,
    COALESCE(AVG(rating) FILTER (WHERE status = 1), 0)::float AS avg_rating,
    COUNT(*) FILTER (WHERE status = 1)::int                   AS total_reviews,
    COUNT(*) FILTER (WHERE status = 1 AND rating = 1)::int    AS rating_1_count,
    COUNT(*) FILTER (WHERE status = 1 AND rating = 2)::int    AS rating_2_count,
    COUNT(*) FILTER (WHERE status = 1 AND rating = 3)::int    AS rating_3_count,
    COUNT(*) FILTER (WHERE status = 1 AND rating = 4)::int    AS rating_4_count,
    COUNT(*) FILTER (WHERE status = 1 AND rating = 5)::int    AS rating_5_count
FROM reviews
WHERE target = $1 AND target_id = $2
`

type GetReviewSummaryParams struct {
	Target   int16 `json:"target"`
	TargetID int32 `json:"target_id"`
}

type GetReviewSummaryRow struct {
	Target       int16   `json:"target"`
	TargetID     int32   `json:"target_id"`
	AvgRating    float64 `json:"avg_rating"`
	TotalReviews int32   `json:"total_reviews"`
	Rating1Count int32   `json:"rating_1_count"`
	Rating2Count int32   `json:"rating_2_count"`
	Rating3Count int32   `json:"rating_3_count"`
	Rating4Count int32   `json:"rating_4_count"`
	Rating5Count int32   `json:"rating_5_count"`
}

func (q *Queries) GetReviewSummary(ctx context.Context, arg GetReviewSummaryParams) (GetReviewSummaryRow, error) {
	row := q.db.QueryRow(ctx, getReviewSummary, arg.Target, arg.TargetID)
	var i GetReviewSummaryRow
	err := row.Scan(
		&i.Target,
		&i.TargetID,
		&i.AvgRating,
		&i.TotalReviews,
		&i.Rating1Count,
		&i.Rating2Count,
		&i.Rating3Count,
		&i.Rating4Count,
		&i.Rating5Count,
	)
	return i, err
}

const hideReview = `-- name: HideReview :one
UPDATE reviews
SET status     = 2,
    updated_at = NOW()
WHERE id = $1 AND status = 1
RETURNING id, author_id, target_id, target, reference_id,
          rating, comment, reply, replied_at, status,
          created_at, updated_at
`

func (q *Queries) HideReview(ctx context.Context, id int64) (Review, error) {
	row := q.db.QueryRow(ctx, hideReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.TargetID,
		&i.Target,
		&i.ReferenceID,
		&i.Rating,
		&i.Comment,
		&i.Reply,
		&i.RepliedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMyReviews = `-- name: ListMyReviews :many
SELECT
    r.id, r.author_id, r.target_id, r.target, r.reference_id,
    r.rating, r.comment, r.reply, r.replied_at, r.status,
    r.created_at, r.updated_at,

    u.name       AS author_name,
    u.avatar_url AS author_avatar
FROM reviews r
JOIN users u ON u.id = r.author_id
WHERE r.author_id = $1
  AND r.status <> 3
  AND ($2::smallint IS NULL OR r.target = $2)
  AND ($3::timestamptz IS NULL
       OR (r.created_at, r.id) < ($3, $4))
ORDER BY r.created_at DESC, r.id DESC
LIMIT $5
`

type ListMyReviewsParams struct {
	AuthorID     int32              `json:"author_id"`
	TargetFilter pgtype.Int2        `json:"target_filter"`
	CursorTime   pgtype.Timestamptz `json:"cursor_time"`
	CursorID     pgtype.Timestamptz `json:"cursor_id"`
	PageSize     int32              `json:"page_size"`
}

type ListMyReviewsRow struct {
	ID           int64              `json:"id"`
	AuthorID     int32              `json:"author_id"`
	TargetID     int32              `json:"target_id"`
	Target       int16              `json:"target"`
	ReferenceID  string             `json:"reference_id"`
	Rating       int16              `json:"rating"`
	Comment      pgtype.Text        `json:"comment"`
	Reply        pgtype.Text        `json:"reply"`
	RepliedAt    pgtype.Timestamptz `json:"replied_at"`
	Status       int16              `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	AuthorName   pgtype.Text        `json:"author_name"`
	AuthorAvatar pgtype.Text        `json:"author_avatar"`
}

func (q *Queries) ListMyReviews(ctx context.Context, arg ListMyReviewsParams) ([]ListMyReviewsRow, error) {
	rows, err := q.db.Query(ctx, listMyReviews,
		arg.AuthorID,
		arg.TargetFilter,
		arg.CursorTime,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyReviewsRow
	for rows.Next() {
		var i ListMyReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.TargetID,
			&i.Target,
			&i.ReferenceID,
			&i.Rating,
			&i.Comment,
			&i.Reply,
			&i.RepliedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyTargetReviews = `-- name: ListMyTargetReviews :many
SELECT
    r.id, r.author_id, r.target_id, r.target, r.reference_id,
    r.rating, r.comment, r.reply, r.replied_at, r.status,
    r.created_at, r.updated_at,

    u.name       AS author_name,
    u.avatar_url AS author_avatar
FROM reviews r
JOIN users u ON u.id = r.author_id
WHERE r.target = $1
  AND r.target_id = $2
  AND r.status <> 3
  AND ($3::bool IS NULL
       OR ($3 = TRUE AND r.reply IS NULL))
  AND ($4::timestamptz IS NULL
       OR (r.created_at, r.id) < ($4, $5))
ORDER BY r.created_at DESC, r.id DESC
LIMIT $6
`

type ListMyTargetReviewsParams struct {
	Target         int16              `json:"target"`
	TargetID       int32              `json:"target_id"`
	OnlyUnanswered pgtype.Bool        `json:"only_unanswered"`
	CursorTime     pgtype.Timestamptz `json:"cursor_time"`
	CursorID       pgtype.Timestamptz `json:"cursor_id"`
	PageSize       int32              `json:"page_size"`
}

type ListMyTargetReviewsRow struct {
	ID           int64              `json:"id"`
	AuthorID     int32              `json:"author_id"`
	TargetID     int32              `json:"target_id"`
	Target       int16              `json:"target"`
	ReferenceID  string             `json:"reference_id"`
	Rating       int16              `json:"rating"`
	Comment      pgtype.Text        `json:"comment"`
	Reply        pgtype.Text        `json:"reply"`
	RepliedAt    pgtype.Timestamptz `json:"replied_at"`
	Status       int16              `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	AuthorName   pgtype.Text        `json:"author_name"`
	AuthorAvatar pgtype.Text        `json:"author_avatar"`
}

func (q *Queries) ListMyTargetReviews(ctx context.Context, arg ListMyTargetReviewsParams) ([]ListMyTargetReviewsRow, error) {
	rows, err := q.db.Query(ctx, listMyTargetReviews,
		arg.Target,
		arg.TargetID,
		arg.OnlyUnanswered,
		arg.CursorTime,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyTargetReviewsRow
	for rows.Next() {
		var i ListMyTargetReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.TargetID,
			&i.Target,
			&i.ReferenceID,
			&i.Rating,
			&i.Comment,
			&i.Reply,
			&i.RepliedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetReviews = `-- name: ListTargetReviews :many
SELECT
    r.id, r.author_id, r.target_id, r.target, r.reference_id,
    r.rating, r.comment, r.reply, r.replied_at, r.status,
    r.created_at, r.updated_at,

    u.name       AS author_name,
    u.avatar_url AS author_avatar
FROM reviews r
JOIN users u ON u.id = r.author_id
WHERE r.target = $1
  AND r.target_id = $2
  AND r.status = 1
  AND ($3::timestamptz IS NULL
       OR (r.created_at, r.id) < ($3, $4))
ORDER BY r.created_at DESC, r.id DESC
LIMIT $5
`

type ListTargetReviewsParams struct {
	Target     int16              `json:"target"`
	TargetID   int32              `json:"target_id"`
	CursorTime pgtype.Timestamptz `json:"cursor_time"`
	CursorID   pgtype.Timestamptz `json:"cursor_id"`
	PageSize   int32              `json:"page_size"`
}

type ListTargetReviewsRow struct {
	ID           int64              `json:"id"`
	AuthorID     int32              `json:"author_id"`
	TargetID     int32              `json:"target_id"`
	Target       int16              `json:"target"`
	ReferenceID  string             `json:"reference_id"`
	Rating       int16              `json:"rating"`
	Comment      pgtype.Text        `json:"comment"`
	Reply        pgtype.Text        `json:"reply"`
	RepliedAt    pgtype.Timestamptz `json:"replied_at"`
	Status       int16              `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	AuthorName   pgtype.Text        `json:"author_name"`
	AuthorAvatar pgtype.Text        `json:"author_avatar"`
}

func (q *Queries) ListTargetReviews(ctx context.Context, arg ListTargetReviewsParams) ([]ListTargetReviewsRow, error) {
	rows, err := q.db.Query(ctx, listTargetReviews,
		arg.Target,
		arg.TargetID,
		arg.CursorTime,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTargetReviewsRow
	for rows.Next() {
		var i ListTargetReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.TargetID,
			&i.Target,
			&i.ReferenceID,
			&i.Rating,
			&i.Comment,
			&i.Reply,
			&i.RepliedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replyToReview = `-- name: ReplyToReview :one
UPDATE reviews
SET reply      = $2,
    replied_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND status = 1
RETURNING id, author_id, target_id, target, reference_id,
          rating, comment, reply, replied_at, status,
          created_at, updated_at
`

type ReplyToReviewParams struct {
	ID    int64       `json:"id"`
	Reply pgtype.Text `json:"reply"`
}

func (q *Queries) ReplyToReview(ctx context.Context, arg ReplyToReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, replyToReview, arg.ID, arg.Reply)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.TargetID,
		&i.Target,
		&i.ReferenceID,
		&i.Rating,
		&i.Comment,
		&i.Reply,
		&i.RepliedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reviewBelongsToAuthor = `-- name: ReviewBelongsToAuthor :one
SELECT EXISTS(
    SELECT 1 FROM reviews WHERE id = $1 AND author_id = $2
) AS belongs
`

type ReviewBelongsToAuthorParams struct {
	ID       int64 `json:"id"`
	AuthorID int32 `json:"author_id"`
}

func (q *Queries) ReviewBelongsToAuthor(ctx context.Context, arg ReviewBelongsToAuthorParams) (bool, error) {
	row := q.db.QueryRow(ctx, reviewBelongsToAuthor, arg.ID, arg.AuthorID)
	var belongs bool
	err := row.Scan(&belongs)
	return belongs, err
}

const reviewExistsForReference = `-- name: ReviewExistsForReference :one
SELECT EXISTS(
    SELECT 1 FROM reviews WHERE author_id = $1 AND reference_id = $2
) AS exists
`

type ReviewExistsForReferenceParams struct {
	AuthorID    int32  `json:"author_id"`
	ReferenceID string `json:"reference_id"`
}

func (q *Queries) ReviewExistsForReference(ctx context.Context, arg ReviewExistsForReferenceParams) (bool, error) {
	row := q.db.QueryRow(ctx, reviewExistsForReference, arg.AuthorID, arg.ReferenceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const unhideReview = `-- name: UnhideReview :one
UPDATE reviews
SET status     = 1,
    updated_at = NOW()
WHERE id = $1 AND status = 2
RETURNING id, author_id, target_id, target, reference_id,
          rating, comment, reply, replied_at, status,
          created_at, updated_at
`

func (q *Queries) UnhideReview(ctx context.Context, id int64) (Review, error) {
	row := q.db.QueryRow(ctx, unhideReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.TargetID,
		&i.Target,
		&i.ReferenceID,
		&i.Rating,
		&i.Comment,
		&i.Reply,
		&i.RepliedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReview = `-- name: UpdateReview :one
UPDATE reviews
SET rating     = $1,
    comment    = $2,
    updated_at = NOW()
WHERE id = $3 AND author_id = $4 AND status = 1
RETURNING id, author_id, target_id, target, reference_id,
          rating, comment, reply, replied_at, status,
          created_at, updated_at
`

type UpdateReviewParams struct {
	Rating   pgtype.Int2 `json:"rating"`
	Comment  pgtype.Text `json:"comment"`
	ID       int64       `json:"id"`
	AuthorID int32       `json:"author_id"`
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReview,
		arg.Rating,
		arg.Comment,
		arg.ID,
		arg.AuthorID,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.TargetID,
		&i.Target,
		&i.ReferenceID,
		&i.Rating,
		&i.Comment,
		&i.Reply,
		&i.RepliedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
