// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteScheduleRulesByLocation = `-- name: DeleteScheduleRulesByLocation :exec
DELETE FROM schedule_rules WHERE location_id = $1
`

func (q *Queries) DeleteScheduleRulesByLocation(ctx context.Context, locationID int32) error {
	_, err := q.db.Exec(ctx, deleteScheduleRulesByLocation, locationID)
	return err
}

const getBookedSlotsForDay = `-- name: GetBookedSlotsForDay :many
SELECT
    a.start_time, a.end_time
FROM appointments a
WHERE a.master_id = $1
  AND a.location_id = $2
  AND a.status IN (1, 2)
  AND a.start_time >= $3
  AND a.start_time <  $4
ORDER BY a.start_time
`

type GetBookedSlotsForDayParams struct {
	MasterID   int32              `json:"master_id"`
	LocationID int32              `json:"location_id"`
	DayStart   pgtype.Timestamptz `json:"day_start"`
	DayEnd     pgtype.Timestamptz `json:"day_end"`
}

type GetBookedSlotsForDayRow struct {
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) GetBookedSlotsForDay(ctx context.Context, arg GetBookedSlotsForDayParams) ([]GetBookedSlotsForDayRow, error) {
	rows, err := q.db.Query(ctx, getBookedSlotsForDay,
		arg.MasterID,
		arg.LocationID,
		arg.DayStart,
		arg.DayEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookedSlotsForDayRow
	for rows.Next() {
		var i GetBookedSlotsForDayRow
		if err := rows.Scan(&i.StartTime, &i.EndTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookedSlotsInRange = `-- name: GetBookedSlotsInRange :many
SELECT
    a.start_time, a.end_time
FROM appointments a
WHERE a.master_id = $1
  AND a.location_id = $2
  AND a.status IN (1, 2)
  AND a.start_time >= $3
  AND a.start_time <  $4
ORDER BY a.start_time
`

type GetBookedSlotsInRangeParams struct {
	MasterID   int32              `json:"master_id"`
	LocationID int32              `json:"location_id"`
	FromTime   pgtype.Timestamptz `json:"from_time"`
	ToTime     pgtype.Timestamptz `json:"to_time"`
}

type GetBookedSlotsInRangeRow struct {
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) GetBookedSlotsInRange(ctx context.Context, arg GetBookedSlotsInRangeParams) ([]GetBookedSlotsInRangeRow, error) {
	rows, err := q.db.Query(ctx, getBookedSlotsInRange,
		arg.MasterID,
		arg.LocationID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookedSlotsInRangeRow
	for rows.Next() {
		var i GetBookedSlotsInRangeRow
		if err := rows.Scan(&i.StartTime, &i.EndTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduleRuleByLocationAndDay = `-- name: GetScheduleRuleByLocationAndDay :one
SELECT
    id, location_id, day_of_week, is_working_day,
    work_start, work_end, rest_start, rest_end,
    buffer_between_slots_mins, slot_step_mins,
    created_at, updated_at
FROM schedule_rules
WHERE location_id = $1 AND day_of_week = $2
`

type GetScheduleRuleByLocationAndDayParams struct {
	LocationID int32 `json:"location_id"`
	DayOfWeek  int16 `json:"day_of_week"`
}

func (q *Queries) GetScheduleRuleByLocationAndDay(ctx context.Context, arg GetScheduleRuleByLocationAndDayParams) (ScheduleRule, error) {
	row := q.db.QueryRow(ctx, getScheduleRuleByLocationAndDay, arg.LocationID, arg.DayOfWeek)
	var i ScheduleRule
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.DayOfWeek,
		&i.IsWorkingDay,
		&i.WorkStart,
		&i.WorkEnd,
		&i.RestStart,
		&i.RestEnd,
		&i.BufferBetweenSlotsMins,
		&i.SlotStepMins,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduleRulesByLocation = `-- name: GetScheduleRulesByLocation :many
SELECT
    id, location_id, day_of_week, is_working_day,
    work_start, work_end, rest_start, rest_end,
    buffer_between_slots_mins, slot_step_mins,
    created_at, updated_at
FROM schedule_rules
WHERE location_id = $1
ORDER BY day_of_week
`

func (q *Queries) GetScheduleRulesByLocation(ctx context.Context, locationID int32) ([]ScheduleRule, error) {
	rows, err := q.db.Query(ctx, getScheduleRulesByLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduleRule
	for rows.Next() {
		var i ScheduleRule
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.DayOfWeek,
			&i.IsWorkingDay,
			&i.WorkStart,
			&i.WorkEnd,
			&i.RestStart,
			&i.RestEnd,
			&i.BufferBetweenSlotsMins,
			&i.SlotStepMins,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertScheduleRule = `-- name: InsertScheduleRule :one
INSERT INTO schedule_rules (
    location_id, day_of_week, is_working_day,
    work_start, work_end, rest_start, rest_end,
    buffer_between_slots_mins, slot_step_mins
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, location_id, day_of_week, is_working_day,
          work_start, work_end, rest_start, rest_end,
          buffer_between_slots_mins, slot_step_mins,
          created_at, updated_at
`

type InsertScheduleRuleParams struct {
	LocationID             int32       `json:"location_id"`
	DayOfWeek              int16       `json:"day_of_week"`
	IsWorkingDay           bool        `json:"is_working_day"`
	WorkStart              pgtype.Time `json:"work_start"`
	WorkEnd                pgtype.Time `json:"work_end"`
	RestStart              pgtype.Time `json:"rest_start"`
	RestEnd                pgtype.Time `json:"rest_end"`
	BufferBetweenSlotsMins int32       `json:"buffer_between_slots_mins"`
	SlotStepMins           int32       `json:"slot_step_mins"`
}

func (q *Queries) InsertScheduleRule(ctx context.Context, arg InsertScheduleRuleParams) (ScheduleRule, error) {
	row := q.db.QueryRow(ctx, insertScheduleRule,
		arg.LocationID,
		arg.DayOfWeek,
		arg.IsWorkingDay,
		arg.WorkStart,
		arg.WorkEnd,
		arg.RestStart,
		arg.RestEnd,
		arg.BufferBetweenSlotsMins,
		arg.SlotStepMins,
	)
	var i ScheduleRule
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.DayOfWeek,
		&i.IsWorkingDay,
		&i.WorkStart,
		&i.WorkEnd,
		&i.RestStart,
		&i.RestEnd,
		&i.BufferBetweenSlotsMins,
		&i.SlotStepMins,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertScheduleRule = `-- name: UpsertScheduleRule :one
INSERT INTO schedule_rules (
    location_id, day_of_week, is_working_day,
    work_start, work_end, rest_start, rest_end,
    buffer_between_slots_mins, slot_step_mins
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (location_id, day_of_week) DO UPDATE SET
    is_working_day            = EXCLUDED.is_working_day,
    work_start                = EXCLUDED.work_start,
    work_end                  = EXCLUDED.work_end,
    rest_start                = EXCLUDED.rest_start,
    rest_end                  = EXCLUDED.rest_end,
    buffer_between_slots_mins = EXCLUDED.buffer_between_slots_mins,
    slot_step_mins            = EXCLUDED.slot_step_mins,
    updated_at                = NOW()
RETURNING id, location_id, day_of_week, is_working_day,
          work_start, work_end, rest_start, rest_end,
          buffer_between_slots_mins, slot_step_mins,
          created_at, updated_at
`

type UpsertScheduleRuleParams struct {
	LocationID             int32       `json:"location_id"`
	DayOfWeek              int16       `json:"day_of_week"`
	IsWorkingDay           bool        `json:"is_working_day"`
	WorkStart              pgtype.Time `json:"work_start"`
	WorkEnd                pgtype.Time `json:"work_end"`
	RestStart              pgtype.Time `json:"rest_start"`
	RestEnd                pgtype.Time `json:"rest_end"`
	BufferBetweenSlotsMins int32       `json:"buffer_between_slots_mins"`
	SlotStepMins           int32       `json:"slot_step_mins"`
}

func (q *Queries) UpsertScheduleRule(ctx context.Context, arg UpsertScheduleRuleParams) (ScheduleRule, error) {
	row := q.db.QueryRow(ctx, upsertScheduleRule,
		arg.LocationID,
		arg.DayOfWeek,
		arg.IsWorkingDay,
		arg.WorkStart,
		arg.WorkEnd,
		arg.RestStart,
		arg.RestEnd,
		arg.BufferBetweenSlotsMins,
		arg.SlotStepMins,
	)
	var i ScheduleRule
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.DayOfWeek,
		&i.IsWorkingDay,
		&i.WorkStart,
		&i.WorkEnd,
		&i.RestStart,
		&i.RestEnd,
		&i.BufferBetweenSlotsMins,
		&i.SlotStepMins,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
