// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_locations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLocationsByService = `-- name: GetLocationsByService :many
SELECT location_id, duration_mins, price, currency, is_active
FROM service_locations WHERE service_id = $1
`

type GetLocationsByServiceRow struct {
	LocationID   int32       `json:"location_id"`
	DurationMins int32       `json:"duration_mins"`
	Price        int32       `json:"price"`
	Currency     string      `json:"currency"`
	IsActive     pgtype.Bool `json:"is_active"`
}

func (q *Queries) GetLocationsByService(ctx context.Context, serviceID int32) ([]GetLocationsByServiceRow, error) {
	rows, err := q.db.Query(ctx, getLocationsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLocationsByServiceRow
	for rows.Next() {
		var i GetLocationsByServiceRow
		if err := rows.Scan(
			&i.LocationID,
			&i.DurationMins,
			&i.Price,
			&i.Currency,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertServiceLocations = `-- name: InsertServiceLocations :exec
INSERT INTO service_locations (service_id, location_id, duration_mins, price, currency, is_active)
SELECT
    $1::int,
    x.location_id,
    x.duration_mins,
    x.price,
    x.currency,
    x.is_active
FROM jsonb_to_recordset($2::jsonb)
     AS x(location_id INT, duration_mins INT, price INT, currency VARCHAR(3), is_active BOOL)
`

type InsertServiceLocationsParams struct {
	ServiceID int32  `json:"service_id"`
	Data      []byte `json:"data"`
}

func (q *Queries) InsertServiceLocations(ctx context.Context, arg InsertServiceLocationsParams) error {
	_, err := q.db.Exec(ctx, insertServiceLocations, arg.ServiceID, arg.Data)
	return err
}

const replaceServiceLocations = `-- name: ReplaceServiceLocations :exec
DELETE FROM service_locations WHERE service_id = $1
`

func (q *Queries) ReplaceServiceLocations(ctx context.Context, serviceID int32) error {
	_, err := q.db.Exec(ctx, replaceServiceLocations, serviceID)
	return err
}

const validateLocationsBelongToMaster = `-- name: ValidateLocationsBelongToMaster :one
SELECT (
    SELECT COUNT(*) FROM locations
    WHERE id = ANY($2::int[]) AND master_id = $1
) = cardinality($2::int[]) AS all_belong
`

type ValidateLocationsBelongToMasterParams struct {
	MasterID    int32   `json:"master_id"`
	LocationIds []int32 `json:"location_ids"`
}

func (q *Queries) ValidateLocationsBelongToMaster(ctx context.Context, arg ValidateLocationsBelongToMasterParams) (bool, error) {
	row := q.db.QueryRow(ctx, validateLocationsBelongToMaster, arg.MasterID, arg.LocationIds)
	var all_belong bool
	err := row.Scan(&all_belong)
	return all_belong, err
}
