// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (master_id, default_service_id, slug, name, description, price, currency, duration_mins)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, master_id, default_service_id, slug, name, description,
          price, currency, duration_mins, is_active, created_at, updated_at
`

type CreateServiceParams struct {
	MasterID         int32       `json:"master_id"`
	DefaultServiceID pgtype.Int4 `json:"default_service_id"`
	Slug             string      `json:"slug"`
	Name             string      `json:"name"`
	Description      pgtype.Text `json:"description"`
	Price            int32       `json:"price"`
	Currency         string      `json:"currency"`
	DurationMins     int32       `json:"duration_mins"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.MasterID,
		arg.DefaultServiceID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Currency,
		arg.DurationMins,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.DefaultServiceID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.DurationMins,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
UPDATE services SET is_active = FALSE, updated_at = NOW()
WHERE id = $1 AND master_id = $2
`

type DeleteServiceParams struct {
	ID       int32 `json:"id"`
	MasterID int32 `json:"master_id"`
}

func (q *Queries) DeleteService(ctx context.Context, arg DeleteServiceParams) error {
	_, err := q.db.Exec(ctx, deleteService, arg.ID, arg.MasterID)
	return err
}

const getDefaultServiceForCopy = `-- name: GetDefaultServiceForCopy :one
SELECT id, category_id, slug, name, description, price, currency, duration_mins
FROM default_services WHERE id = $1 AND is_active = TRUE
`

type GetDefaultServiceForCopyRow struct {
	ID           int32       `json:"id"`
	CategoryID   int32       `json:"category_id"`
	Slug         string      `json:"slug"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	Price        int32       `json:"price"`
	Currency     string      `json:"currency"`
	DurationMins int32       `json:"duration_mins"`
}

func (q *Queries) GetDefaultServiceForCopy(ctx context.Context, id int32) (GetDefaultServiceForCopyRow, error) {
	row := q.db.QueryRow(ctx, getDefaultServiceForCopy, id)
	var i GetDefaultServiceForCopyRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.DurationMins,
	)
	return i, err
}

const getMyServices = `-- name: GetMyServices :many
SELECT
    s.id, s.master_id, s.default_service_id, s.slug, s.name, s.description,
    s.price, s.currency, s.duration_mins, s.is_active,
    s.created_at, s.updated_at,
    COALESCE((
        SELECT json_agg(json_build_object(
            'location_id', sl.location_id,
            'duration_mins', COALESCE(NULLIF(sl.duration_mins, 0), s.duration_mins),
            'price', COALESCE(NULLIF(sl.price, 0), s.price),
            'is_active', sl.is_active
        ) ORDER BY sl.location_id)
        FROM service_locations sl
        WHERE sl.service_id = s.id
    ), '[]'::json) AS locations_json
FROM services s
WHERE s.master_id = $1 AND s.is_active = TRUE
ORDER BY s.id
`

type GetMyServicesRow struct {
	ID               int32              `json:"id"`
	MasterID         int32              `json:"master_id"`
	DefaultServiceID pgtype.Int4        `json:"default_service_id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Description      pgtype.Text        `json:"description"`
	Price            int32              `json:"price"`
	Currency         string             `json:"currency"`
	DurationMins     int32              `json:"duration_mins"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	LocationsJson    interface{}        `json:"locations_json"`
}

func (q *Queries) GetMyServices(ctx context.Context, masterID int32) ([]GetMyServicesRow, error) {
	rows, err := q.db.Query(ctx, getMyServices, masterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMyServicesRow
	for rows.Next() {
		var i GetMyServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.MasterID,
			&i.DefaultServiceID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.DurationMins,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocationsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT
    s.id, s.master_id, s.default_service_id, s.slug, s.name, s.description,
    s.price, s.currency, s.duration_mins, s.is_active,
    s.created_at, s.updated_at,
    COALESCE((
        SELECT json_agg(json_build_object(
            'location_id', sl.location_id,
            'duration_mins', COALESCE(NULLIF(sl.duration_mins, 0), s.duration_mins),
            'price', COALESCE(NULLIF(sl.price, 0), s.price),
            'is_active', sl.is_active
        ) ORDER BY sl.location_id)
        FROM service_locations sl
        WHERE sl.service_id = s.id
    ), '[]'::json) AS locations_json
FROM services s
WHERE s.id = $1
`

type GetServiceByIDRow struct {
	ID               int32              `json:"id"`
	MasterID         int32              `json:"master_id"`
	DefaultServiceID pgtype.Int4        `json:"default_service_id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Description      pgtype.Text        `json:"description"`
	Price            int32              `json:"price"`
	Currency         string             `json:"currency"`
	DurationMins     int32              `json:"duration_mins"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	LocationsJson    interface{}        `json:"locations_json"`
}

func (q *Queries) GetServiceByID(ctx context.Context, id int32) (GetServiceByIDRow, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i GetServiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.DefaultServiceID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.DurationMins,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationsJson,
	)
	return i, err
}

const serviceSlugExists = `-- name: ServiceSlugExists :one
SELECT EXISTS(
    SELECT 1 FROM services
    WHERE master_id = $1 AND slug = $2 AND id <> COALESCE($3, 0)
) AS exists
`

type ServiceSlugExistsParams struct {
	MasterID  int32       `json:"master_id"`
	Slug      string      `json:"slug"`
	ExcludeID pgtype.Int4 `json:"exclude_id"`
}

func (q *Queries) ServiceSlugExists(ctx context.Context, arg ServiceSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, serviceSlugExists, arg.MasterID, arg.Slug, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET description   = COALESCE($1, description),
    duration_mins = COALESCE($2, duration_mins),
    price         = COALESCE($3, price),
    updated_at    = NOW()
WHERE id = $4 AND master_id = $5
RETURNING id, master_id, default_service_id, slug, name, description,
          price, currency, duration_mins, is_active, created_at, updated_at
`

type UpdateServiceParams struct {
	Description  pgtype.Text `json:"description"`
	DurationMins pgtype.Int4 `json:"duration_mins"`
	Price        pgtype.Int4 `json:"price"`
	ID           int32       `json:"id"`
	MasterID     int32       `json:"master_id"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.Description,
		arg.DurationMins,
		arg.Price,
		arg.ID,
		arg.MasterID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.DefaultServiceID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.DurationMins,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateServicesMinPrice = `-- name: UpdateServicesMinPrice :exec
UPDATE masters SET min_price = (
    SELECT COALESCE(MIN(price), 0) FROM services
    WHERE master_id = $1 AND is_active = TRUE
), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateServicesMinPrice(ctx context.Context, masterID int32) error {
	_, err := q.db.Exec(ctx, updateServicesMinPrice, masterID)
	return err
}
