// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserRoles = `-- name: AddUserRoles :exec
INSERT INTO user_roles (user_id, role_id)
SELECT $1, unnest($2::int[])
ON CONFLICT DO NOTHING
`

type AddUserRolesParams struct {
	UserID  int32   `json:"user_id"`
	Column2 []int32 `json:"column_2"`
}

func (q *Queries) AddUserRoles(ctx context.Context, arg AddUserRolesParams) error {
	_, err := q.db.Exec(ctx, addUserRoles, arg.UserID, arg.Column2)
	return err
}

const assignRole = `-- name: AssignRole :exec

INSERT INTO user_roles (user_id, role_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignRoleParams struct {
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}

// ============================================================
// ROLES
// ============================================================
func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.Exec(ctx, assignRole, arg.UserID, arg.RoleID)
	return err
}

const createUser = `-- name: CreateUser :one

WITH inserted_user AS (
    INSERT INTO users (name, email, password_hash)
    VALUES ($1, $2, $3)
    RETURNING id, name, email, avatar_url, timezone, email_verified, created_at, updated_at
),
inserted_roles AS (
    INSERT INTO user_roles (user_id, role_id)
    SELECT iu.id, r.role_id
    FROM inserted_user iu
    CROSS JOIN unnest($4::int[]) AS r(role_id)
    RETURNING user_id
)
SELECT iu.id, iu.name, iu.email, iu.avatar_url, iu.timezone, iu.email_verified, iu.created_at, iu.updated_at
FROM inserted_user iu
JOIN inserted_roles ir ON ir.user_id = iu.id
GROUP BY iu.id, iu.name, iu.email, iu.avatar_url, iu.timezone, iu.email_verified, iu.created_at, iu.updated_at
`

type CreateUserParams struct {
	Name         pgtype.Text `json:"name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	RoleIds      []int32     `json:"role_ids"`
}

type CreateUserRow struct {
	ID            int32              `json:"id"`
	Name          pgtype.Text        `json:"name"`
	Email         string             `json:"email"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	Timezone      pgtype.Text        `json:"timezone"`
	EmailVerified pgtype.Bool        `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// ============================================================
// USERS
// ============================================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.RoleIds,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Timezone,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    u.id, u.name, u.email, u.password_hash, u.avatar_url, u.timezone, u.email_verified,
    u.created_at, u.updated_at,
    array_agg(ur.role_id ORDER BY ur.role_id)::int[] AS role_ids
FROM users u
LEFT JOIN user_roles ur ON ur.user_id = u.id
WHERE u.email = $1
GROUP BY u.id
`

type GetUserByEmailRow struct {
	ID            int32              `json:"id"`
	Name          pgtype.Text        `json:"name"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	Timezone      pgtype.Text        `json:"timezone"`
	EmailVerified pgtype.Bool        `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	RoleIds       []int32            `json:"role_ids"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Timezone,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleIds,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    u.id, u.name, u.email, u.avatar_url, u.timezone, u.email_verified,
    u.created_at, u.updated_at,
    array_agg(ur.role_id ORDER BY ur.role_id)::int[] AS role_ids
FROM users u
LEFT JOIN user_roles ur ON ur.user_id = u.id
WHERE u.id = $1
GROUP BY u.id
`

type GetUserByIDRow struct {
	ID            int32              `json:"id"`
	Name          pgtype.Text        `json:"name"`
	Email         string             `json:"email"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	Timezone      pgtype.Text        `json:"timezone"`
	EmailVerified pgtype.Bool        `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	RoleIds       []int32            `json:"role_ids"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Timezone,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleIds,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT role_id FROM user_roles WHERE user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var role_id int32
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasRole = `-- name: HasRole :one
SELECT EXISTS(
    SELECT 1 FROM user_roles WHERE user_id = $1 AND role_id = $2
) AS has_role
`

type HasRoleParams struct {
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}

func (q *Queries) HasRole(ctx context.Context, arg HasRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasRole, arg.UserID, arg.RoleID)
	var has_role bool
	err := row.Scan(&has_role)
	return has_role, err
}

const removeRole = `-- name: RemoveRole :exec
DELETE FROM user_roles WHERE user_id = $1 AND role_id = $2
`

type RemoveRoleParams struct {
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}

func (q *Queries) RemoveRole(ctx context.Context, arg RemoveRoleParams) error {
	_, err := q.db.Exec(ctx, removeRole, arg.UserID, arg.RoleID)
	return err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users SET email_verified = TRUE, updated_at = NOW() WHERE id = $1 AND email_verified = FALSE
`

func (q *Queries) SetEmailVerified(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, setEmailVerified, id)
	return err
}

const setUserRoles = `-- name: SetUserRoles :exec
DELETE FROM user_roles WHERE user_id = $1
`

func (q *Queries) SetUserRoles(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, setUserRoles, userID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           int32  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name       = COALESCE($1, name),
    avatar_url = COALESCE($2, avatar_url),
    timezone   = COALESCE($3, timezone),
    updated_at = NOW()
WHERE id = $4
RETURNING id, name, email, avatar_url, timezone, email_verified, created_at, updated_at
`

type UpdateUserParams struct {
	Name      pgtype.Text `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	Timezone  pgtype.Text `json:"timezone"`
	ID        int32       `json:"id"`
}

type UpdateUserRow struct {
	ID            int32              `json:"id"`
	Name          pgtype.Text        `json:"name"`
	Email         string             `json:"email"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	Timezone      pgtype.Text        `json:"timezone"`
	EmailVerified pgtype.Bool        `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.AvatarUrl,
		arg.Timezone,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Timezone,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
