// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_notifications.sql

package db

import (
	"context"
)

const createDefaultNotificationSettings = `-- name: CreateDefaultNotificationSettings :one
INSERT INTO notification_settings (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
RETURNING
    user_id, email_enabled, telegram_enabled, sms_enabled, push_enabled,
    muted_types, reminder_24h, reminder_2h, reminder_30m, updated_at
`

func (q *Queries) CreateDefaultNotificationSettings(ctx context.Context, userID int32) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, createDefaultNotificationSettings, userID)
	var i NotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.EmailEnabled,
		&i.TelegramEnabled,
		&i.SmsEnabled,
		&i.PushEnabled,
		&i.MutedTypes,
		&i.Reminder24h,
		&i.Reminder2h,
		&i.Reminder30m,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelEnabled = `-- name: GetChannelEnabled :one
SELECT
    email_enabled,
    telegram_enabled,
    sms_enabled,
    push_enabled
FROM notification_settings
WHERE user_id = $1
`

type GetChannelEnabledRow struct {
	EmailEnabled    bool `json:"email_enabled"`
	TelegramEnabled bool `json:"telegram_enabled"`
	SmsEnabled      bool `json:"sms_enabled"`
	PushEnabled     bool `json:"push_enabled"`
}

func (q *Queries) GetChannelEnabled(ctx context.Context, userID int32) (GetChannelEnabledRow, error) {
	row := q.db.QueryRow(ctx, getChannelEnabled, userID)
	var i GetChannelEnabledRow
	err := row.Scan(
		&i.EmailEnabled,
		&i.TelegramEnabled,
		&i.SmsEnabled,
		&i.PushEnabled,
	)
	return i, err
}

const getNotificationSettings = `-- name: GetNotificationSettings :one
SELECT
    user_id, email_enabled, telegram_enabled, sms_enabled, push_enabled,
    muted_types, reminder_24h, reminder_2h, reminder_30m, updated_at
FROM notification_settings
WHERE user_id = $1
`

func (q *Queries) GetNotificationSettings(ctx context.Context, userID int32) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, getNotificationSettings, userID)
	var i NotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.EmailEnabled,
		&i.TelegramEnabled,
		&i.SmsEnabled,
		&i.PushEnabled,
		&i.MutedTypes,
		&i.Reminder24h,
		&i.Reminder2h,
		&i.Reminder30m,
		&i.UpdatedAt,
	)
	return i, err
}

const isTypeMuted = `-- name: IsTypeMuted :one
SELECT EXISTS(
    SELECT 1 FROM notification_settings
    WHERE user_id = $1 AND $2 = ANY(muted_types)
) AS muted
`

type IsTypeMutedParams struct {
	UserID     int32   `json:"user_id"`
	MutedTypes []int16 `json:"muted_types"`
}

func (q *Queries) IsTypeMuted(ctx context.Context, arg IsTypeMutedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTypeMuted, arg.UserID, arg.MutedTypes)
	var muted bool
	err := row.Scan(&muted)
	return muted, err
}

const updateNotificationSettings = `-- name: UpdateNotificationSettings :one
INSERT INTO notification_settings (
    user_id, email_enabled, telegram_enabled, sms_enabled, push_enabled,
    muted_types, reminder_24h, reminder_2h, reminder_30m
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id) DO UPDATE SET
    email_enabled    = EXCLUDED.email_enabled,
    telegram_enabled = EXCLUDED.telegram_enabled,
    sms_enabled      = EXCLUDED.sms_enabled,
    push_enabled     = EXCLUDED.push_enabled,
    muted_types      = EXCLUDED.muted_types,
    reminder_24h     = EXCLUDED.reminder_24h,
    reminder_2h      = EXCLUDED.reminder_2h,
    reminder_30m     = EXCLUDED.reminder_30m,
    updated_at       = NOW()
RETURNING
    user_id, email_enabled, telegram_enabled, sms_enabled, push_enabled,
    muted_types, reminder_24h, reminder_2h, reminder_30m, updated_at
`

type UpdateNotificationSettingsParams struct {
	UserID          int32   `json:"user_id"`
	EmailEnabled    bool    `json:"email_enabled"`
	TelegramEnabled bool    `json:"telegram_enabled"`
	SmsEnabled      bool    `json:"sms_enabled"`
	PushEnabled     bool    `json:"push_enabled"`
	MutedTypes      []int16 `json:"muted_types"`
	Reminder24h     bool    `json:"reminder_24h"`
	Reminder2h      bool    `json:"reminder_2h"`
	Reminder30m     bool    `json:"reminder_30m"`
}

func (q *Queries) UpdateNotificationSettings(ctx context.Context, arg UpdateNotificationSettingsParams) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, updateNotificationSettings,
		arg.UserID,
		arg.EmailEnabled,
		arg.TelegramEnabled,
		arg.SmsEnabled,
		arg.PushEnabled,
		arg.MutedTypes,
		arg.Reminder24h,
		arg.Reminder2h,
		arg.Reminder30m,
	)
	var i NotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.EmailEnabled,
		&i.TelegramEnabled,
		&i.SmsEnabled,
		&i.PushEnabled,
		&i.MutedTypes,
		&i.Reminder24h,
		&i.Reminder2h,
		&i.Reminder30m,
		&i.UpdatedAt,
	)
	return i, err
}
