syntax = "proto3";

package service.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/MuslimIT-dev/Calendly_GetCourse/backend/gen/go/service/v1;servicev1";

// ============================================================
// ENTITIES
// ============================================================

message ServiceLocation {
    string location_id   = 1;
    int32  duration_mins = 2;
    int32  price         = 3;
    bool   is_active     = 4;
}

message Service {
    string id            = 1;
    string slug          = 2;
    string name          = 3;
    string description   = 4;

    // base data
    int32  duration_mins = 5;
    int32  price         = 6;

    repeated ServiceLocation locations = 7;

    bool is_active = 8;

    google.protobuf.Timestamp created_at = 9;
    google.protobuf.Timestamp updated_at = 10;
    string default_service_id = 11;
    string currency           = 12;
}

// ============================================================
// REQUESTS / RESPONSES
// ============================================================

message GetMyServicesRequest {}

message GetMyServicesResponse {
    repeated Service services = 1;
}

message AddServiceRequest {
    string default_id      = 1;
    string new_description = 2;  // "" = take from the temp
    int32  duration_mins   = 3;
    int32  price           = 4;
    string curremcy        = 5;
    repeated ServiceLocation locations = 6;
}

message AddServiceResponse {
    Service service = 1;
}

message UpdateServiceRequest {
    string id            = 1;
    string description   = 2;
    int32  duration_mins = 3;
    int32  price         = 4;
    repeated ServiceLocation locations = 5;
}

message UpdateServiceResponse {
    Service service = 1;
}

message DeleteServiceRequest {
    string id = 1;
}

message DeleteServiceResponse {}

// ============================================================
// SERVICES
// ============================================================

service ServiceService {
    rpc GetMyServices(GetMyServicesRequest) returns (GetMyServicesResponse);
    rpc AddService(AddServiceRequest)       returns (AddServiceResponse);
    rpc UpdateService(UpdateServiceRequest) returns (UpdateServiceResponse);
    rpc DeleteService(DeleteServiceRequest) returns (DeleteServiceResponse);
}